// ═══════════════════════════════════════════════════════════════════
// game_changelog.js 補丁 v3.5.17 + v3.5.16 + v3.5.15 + v3.5.14 + v3.5.13
// 加到 GAME_CHANGELOG 陣列最前面(時間新到舊)
//   → v3.5.17 物件放最前面(最新)
//   → v3.5.16 物件放第二
//   → v3.5.15 物件放第三
//   → v3.5.14 物件放第四
//   → v3.5.13 物件放第五
// ═══════════════════════════════════════════════════════════════════

{ ver:'v3.5.17', brief:[
  '📦 開放「學生授權後可安裝完整遊戲」(老師策略 B:一台一台核准)',
  '🎉 老師按下「核准」後,學生畫面自動跑預載讀條(免重整)',
  '🛡 保護機制:沒授權的學生跟舊版完全一樣(直接抓 GitHub,不會 SW 干擾)',
  '🔄 已裝好的學生授權到期後不會被清除 cache(可繼續離線使用既有資源)',
], items:[
  '【背景】老師 2026/5/22 決議用 v3.5.0 寫好的「下載授權系統」做流量管制:',
  '・老師站在 iPad 旁邊,在管理員後台按一下「✅ 核准」 → 該台學生立刻開始預載',
  '・等該台讀條跑完 → 老師移到下一台,再核准下一位學生',
  '・任何時刻只有「老師剛剛核准」的學生會抓 GitHub,29 台不會撞 NAT 限流',
  '',
  '【實作差異對照】',
  '・v3.5.15 之前:_PWA_DISABLED 寫死 true,所有人都被擋(緊急止血)',
  '・v3.5.16:管理員放行,學生仍擋',
  '・v3.5.17:管理員 OR 有效下載授權 OR 已安裝過 三條件任一即放行',
  '',
  '【修補位置】',
  '・index.html (line ~68520) bootPWA 守門邏輯重寫:',
  '   _allowPwa = _isAdmin || _hasValidPermission || _alreadyInstalled',
  '   並改良 SW unregister 規則:只對「未授權且未安裝過」的玩家清舊 SW,',
  '   避免好不容易裝完的學生因 race condition 被清掉 cache',
  '・index.html (line ~68735) _initDownloadAuth onSnapshot 回呼:',
  '   偵測「權限從非 approved 轉成 approved」事件 → 主動呼叫 _lxpsPWA.boot()',
  '   學生不必重整頁面,老師核准 0.5 秒內畫面自動跑讀條',
  '・index.html (line ~3018) onAuth 登入後分兩段啟動 PWA:',
  '   - 1.5 秒:確認管理員身分 → boot',
  '   - 3.5 秒:確認學生有效授權已從雲端載入 → boot',
  '   (預留充裕緩衝避免 onSnapshot 還沒回來就誤判沒授權)',
  '',
  '【保留的安全網】',
  '・學生「申請下載權限」的 24 小時期限機制完全沿用 v3.5.0 設計',
  '・學生需要先送出申請、老師在管理員後台核准,才會解鎖預載功能',
  '・「下載安裝完整遊戲」按鈕仍維持「授權後才顯示」原則',
  '・學生不會自己手動安裝,完全跟隨老師節奏',
  '',
  '【測試 SOP】',
  '・第 1 階段(老師管理員帳號):',
  '   - 用管理員帳號登入,console 應看到「🛠️ [v3.5.16] 管理員登入確認,重新啟動 PWA」',
  '   - 過幾秒應看到「⚡ 首次安裝中,請保持網路連線...」全螢幕讀條',
  '   - 讀條跑完後關網路重新整理 → 應該還能正常進首頁(確認離線可玩)',
  '・第 2 階段(學生帳號):',
  '   - 用學生帳號登入(沒申請過下載)',
  '   - console 應看到「[PWA] 未授權,不啟動 Service Worker...」(學生端跟舊版一樣)',
  '   - 學生點「📩 申請下載安裝權限」→ 送出',
  '   - 老師在管理員後台按「✅ 批准」',
  '   - 學生畫面 0.5-1 秒內應自動跑出「⚡ 首次安裝中」讀條 ← 關鍵驗證點',
  '   - 讀條跑完 → 可加入主畫面 → 從桌面圖示開啟可離線玩',
  '・第 3 階段(29 台一台一台跑):',
  '   - 老師核准 A → 等 A 讀條跑完(觀察「✓ 安裝完成!」)→ 核准 B',
  '   - 預估每台 5-10 分鐘,29 台共 2.5-5 小時(可分多天)',
  '',
  '【部署提醒】',
  '・sw.js 的 SW_VERSION 需手動同步升到 v3.5.17',
  '・若要恢復完全停用學生端 PWA,請看 bootPWA 內 v3.5.17 區塊註解修改放行條件',
  '・CDN 升級(jsDelivr)與 Firebase Blaze 雖然「不阻擋上線」,但完成後流量更穩,',
  '   建議老師仍將兩件事排入下學期 TODO',
] },

{ ver:'v3.5.16', brief:[
  '🎁 修補設計者英雄獎勵發送失敗:加入 5 次自動 retry + 等雲端就緒',
  '💾 戰鬥中斷可回到未完成戰鬥:離場自動存檔(三層事件)+ 進度雙保險',
  '🔒 打到一半被切帳號跳首頁:被踢前強制存戰鬥快照,並提示「進度已保留」',
  '⏰ 戰鬥中暫停閒置自動登出倒數(避免打 BOSS 時 30 分到被強制踢出)',
], items:[
  '【背景】老師 2026/5/22 回報 3 個學生實測痛點:',
  '・(1) 部分設計者英雄獎勵發不出去',
  '・(2) 打 BOSS 戰到一半突然跳出遊戲,沒辦法回到上次戰鬥,白白浪費時間',
  '・(3) 有同學打到一半被切換帳號跳回首頁,遺失遊戲進度',
  '',
  '【修補 #1:設計者英雄獎勵發送失敗】',
  '・根因:_grantStudentDesignerHero 在登入 1.8 秒後「試一次」就結束。',
  '   但 gameCloudSave 內部會檢查 window._progressLoaded:',
  '     - 若雲端載入慢/超時/失敗 → _progressLoaded=false',
  '     - → gameCloudSave 直接拒絕寫入(避免空資料覆蓋雲端)',
  '   結果 advSaveUnlockedHero 只進到 localStorage,雲端從沒收到設計者英雄',
  '   下次清本機(換帳號清理/閒置 reload)時就遺失',
  '・修法:',
  '   - 改成 async 函式,每次嘗試前 await _waitForCloudReady(15s) 等雲端就緒',
  '   - 5 次 retry 排程(立即/5s/15s/30s/60s/120s,共 6 次嘗試)',
  '   - 用 window._designerHeroGrantState 追蹤狀態,確認本地 + 雲端都成功才結束',
  '   - 同一登入循環內只觸發一次完整 retry 流程(避免重複)',
  '・實作位置:index.html line ~76761 (_grantStudentDesignerHero 重寫為 async)',
  '・onAuth 觸發點(line ~2977)也加上 .catch 防止 unhandled rejection',
  '',
  '【修補 #2:戰鬥中斷可回到未完成戰鬥】',
  '・根因:舊版快照系統有 3 個漏洞',
  '   - _saveBattleRoundSnapshot 只在 startTurn 開頭觸發 → 玩家在「同回合內」跳出時,',
  '     最新一回合的進度沒有被存(尤其 iPad Safari 切後台、頁面回收的情境)',
  '   - 沒有 beforeunload / pagehide 強制存快照 → iOS Safari 殺 page 時雲端來不及同步',
  '   - 世界 BOSS 戰快照雖然存了,但連線層 _wbNet 重建很複雜,單純走 _advRestoreBattleState',
  '     不夠 → 玩家「續戰」進去看到空白戰場',
  '・修法:',
  '   - 新增 window._forceSaveBattleSnapshotAndSync(reason) 對外 API',
  '     立刻「存 localStorage + 寫雲端」,跨各種離開路徑統一使用',
  '   - 註冊 beforeunload + pagehide + visibilitychange→hidden 三層事件,',
  '     戰鬥中 (G.round>=1) 就強制呼叫上面的 API',
  '   - 世界 BOSS 戰排除自動續戰:_advCheckCrashRecovery 偵測到 worldboss 快照時,',
  '     不嘗試還原戰場,改顯示「上次世界 BOSS 戰中斷,進度已保留在雲端,請從關卡選擇重新加入」',
  '・實作位置:',
  '   - index.html line ~37961 (新增 _forceSaveBattleSnapshotAndSync + 三層離場事件監聽)',
  '   - index.html line ~42778 (_advCheckCrashRecovery 加 worldboss 排除分支)',
  '',
  '【修補 #3:打到一半被切帳號跳首頁】',
  '・根因:Session 心跳每 5 秒檢查一次,只要其他裝置登入相同帳號就被踢回首頁。',
  '   學校平板共用情境下,別的學生登入同帳號或誤觸都會踢掉,且若戰鬥未走到下一回合,',
  '   雲端 advSnapshot 還沒同步 → 進度直接遺失',
  '・修法:',
  '   - _checkHeartbeat 偵測到 kicked 狀態時,「先」呼叫 _forceSaveBattleSnapshotAndSync',
  '     再去 _trySaveSafeIfHealthier(避免被守門擋下)',
  '   - _showKickedNotice 加偵測「是否在戰鬥中」,若是則在被踢視窗中加綠色提示框:',
  '     「🛡️ 本場「XX冒險」進度已自動保存,可從原裝置續戰」',
  '   - 雙保險:_showKickedNotice 進入時也再呼叫一次 _forceSaveBattleSnapshotAndSync',
  '・實作位置:',
  '   - index.html line ~3030 (_checkHeartbeat kicked 分支補存快照)',
  '   - index.html line ~75726 (_showKickedNotice 戰鬥提示框 + 雙保險)',
  '',
  '【修補 #4:戰鬥中暫停閒置自動登出倒數】',
  '・根因:閒置 30 分鐘就強制登出 reload,但玩家在 BOSS 戰中可能正在思考題目/查書,',
  '   倒數到時被強制踢出 → 進度遺失(配合 #2 的快照修補,理論上可救,但被踢觸發 reload',
  '   有 race condition,直接暫停倒數最穩)',
  '・修法:',
  '   - _tick 函式內,若 _adventureMode=true 且 G.round>=1 且結算未顯示 → 持續更新',
  '     _lastActivityTs(等於暫停倒數),且關閉警告 modal',
  '   - 玩家離開戰鬥後,倒數才開始真正計時',
  '   - _doAutoLogout 也先呼叫 _forceSaveBattleSnapshotAndSync 才登出 reload',
  '・實作位置:',
  '   - index.html line ~56546 (_tick 加戰鬥中暫停分支)',
  '   - index.html line ~56501 (_doAutoLogout 補存快照)',
  '',
  '【測試 SOP】',
  '・設計者英雄:設計者帳號登入後 → console 應出現「🎁 [設計者英雄補發] #1/6 ... 本地=true, 雲端=true」',
  '   若第 1 次失敗應看到 #2/6、#3/6 連續嘗試,直到雲端=true',
  '・戰鬥中斷:打 BOSS 到第 2 回合 → 直接關瀏覽器 → 重新開啟 →',
  '   登入完成 800ms 後應出現「偵測到未完成的冒險」彈窗,按「繼續這場冒險」可還原戰場',
  '   世界 BOSS 戰中斷則顯示「🌋 上次的世界 BOSS 戰中斷了」提示',
  '・被切換帳號:在 A 裝置打 BOSS → 在 B 裝置登入同帳號 →',
  '   A 裝置 5 秒內彈被踢視窗,內有綠色「進度已自動保存」提示框 →',
  '   重整 A 裝置/重新登入 → 應出現續戰提示',
  '・閒置不會踢出戰鬥:打 BOSS 中放著不動 30 分鐘 → 不應彈倒數視窗,console 也不會觸發',
  '・部署提醒:sw.js 的 SW_VERSION 需手動同步升到 v3.5.16',
] },

{ ver:'v3.5.15', brief:[
  '🏅 修補 BUG:有同學英雄 11 級卻沒解鎖「初顯鋒芒」獎章',
  '🔧 升級時自動觸發英雄等級獎章補解鎖(10/30/50 級)',
  '🔧 雲端載入英雄等級後立刻補檢查獎章(解決時序問題)',
  '🔧 啟動時自動掃描已有等級補解鎖(救已過 Lv10 但沒解鎖的歷史資料)',
], items:[
  '【BUG 背景】',
  '・老師 2026/5/22 回報:有同學英雄已升到 11 級,「初顯鋒芒(任意英雄達到 Lv10)」獎章卻沒解鎖',
  '・分析後發現有「兩個並存的 BUG」造成這個現象',
  '',
  '【BUG #1:_checkMedalHeroLevel 函式定義了卻從未被呼叫】',
  '・函式 _checkMedalHeroLevel(heroName, level) 寫得很完整(line 74688):',
  '   - level >= 10 → 解鎖 hero_lv10',
  '   - level >= 30 → 解鎖 hero_lv30',
  '   - level >= 50 → 解鎖 hero_lv50 + 三隻 MAX 判定 three_max',
  '・但 grep 整個 index.html 發現「沒有任何 callsite」呼叫這個函式',
  '・結果:英雄升到 10/30/50 級永遠不會觸發對應獎章解鎖',
  '・修法:在 addHeroExp 升級成功處(line ~61397)加上呼叫,',
  '   每次升級都把當前等級傳進去做檢查',
  '',
  '【BUG #2:雲端 merge _heroLevels 後沒重新檢查獎章】',
  '・時序問題:',
  '   1. App 啟動 → _heroLevels = {} (空)',
  '   2. _loadMedals 跑(無補檢查)',
  '   3. _checkMedalsOnLogin 跑(line 75092 檢查 _heroLevels,但此時是空的)',
  '   4. 雲端載入完成 → _heroLevels 變成 {熊熊:11, ...}',
  '   5. ❌ 沒有觸發任何獎章重檢查 → 11 級的熊熊不會解鎖',
  '・修法:在雲端 merge 完 _heroLevels 後(line ~56677),',
  '   立刻掃描所有英雄找最高等級並呼叫 _checkMedalHeroLevel',
  '・fallback 路徑(雲端直接覆蓋本地的 catch 分支)也加同樣補檢查',
  '',
  '【補強:_loadMedals 啟動時補檢查】',
  '・在 _loadMedals 完成後(line ~74041)用 setTimeout(100ms) 延遲',
  '   主動掃描 _heroLevels / advGetUnlockedHeroes / 知識幣等里程碑數據,',
  '   把「達標但漏解鎖」的歷史獎章一次性補上',
  '・設計理由:未來新增新獎章類型或修補舊 hook 時,這個「啟動掃描」是穩定的兜底',
  '',
  '【現有同學的補救】',
  '・部署 v3.5.15 後,所有同學重整網頁登入時:',
  '   - _loadMedals → setTimeout 100ms 後補檢查(本地有資料的情況)',
  '   - 雲端 merge 完成 _heroLevels → 立即補檢查(雲端載入完成後)',
  '   - 兩重保險,確保「歷史已達 Lv10/30/50 但漏解鎖的英雄」獲得正確獎章',
  '',
  '【實作位置】',
  '・index.html (line ~61397) — addHeroExp 升級時呼叫 _checkMedalHeroLevel',
  '・index.html (line ~56677) — 雲端 merge _heroLevels 後立即補檢查',
  '・index.html (line ~56697) — fallback 路徑(catch 分支)也補檢查',
  '・index.html (line ~74047) — _loadMedals 後 setTimeout 100ms 補檢查',
  '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.15',
  '',
  '【部署提醒】',
  '・sw.js 的 SW_VERSION 需手動同步升到 v3.5.15',
  '・同學重新進入遊戲後應看到 console「[獎章補檢查] 雲端載入後掃描英雄等級,最高 LvXX」',
  '・如果之前漏解鎖,獎章會在重新登入時自動補上(無須手動操作)',
] },

{ ver:'v3.5.14', brief:[
  '🛡 確認並修補:世界 BOSS 任何一次受傷都不會超過「炎之意志」5000 上限',
  '⚡ 修補爆擊額外傷害可繞 cap 的漏洞(主傷害 5000 + 爆擊 1500 = 6500 → 修正為 5000)',
], items:[
  '【背景】',
  '・老師 2026/5/22 要求確認世界 BOSS 一次不會受到超過 5000 傷害',
  '・系統性掃描所有「target.curHp =」「curHp -=」直接扣血路徑',
  '',
  '【發現 BUG:爆擊額外傷害繞過 cap】',
  '・症狀:主 doDmg 路徑(line 21054)已被 cap 到 5000,',
  '         但爆擊觸發時 line 21142 會額外扣 _critExtra(= 5000 × 30% = 1500),',
  '         結果單次受 6500 傷害,違反「炎之意志單次受傷上限 1% maxHp」設計',
  '・修法:對維蘇威的爆擊額外傷害 _critExtra 再跑一次 _wbApplyBossDmgCap',
  '',
  '【實作位置】',
  '・index.html (line ~21142) — 爆擊額外傷害補扣對維蘇威也走 _wbApplyBossDmgCap',
  '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.14',
] },

{ ver:'v3.5.13', brief:[
  '🔒 [關鍵安全修補] 修補 4 個會「無條件秒殺世界 BOSS」的英雄技能/狀態漏洞',
  '⚖️ 死亡宣告(deathmark)觸發時對 BOSS 改 20% HP 傷害,不再剩 1 HP',
  '🩸 吸血鬼「靈魂收割」對 BOSS 改 20% HP 傷害',
  '💀 鋁合金暴龍爆發「死神龍王登場」收割對 BOSS 改主傷害 50% 追加',
  '⚖️ 修正地府酋長「審判終結」到期判定的 typo bug',
], items:[
  '【事件背景】',
  '・老師 2026/5/22 緊急回報:學生用「暗法師 + 吸血鬼」把世界 BOSS 維蘇威從 90% HP 一招秒',
  '・系統性修補所有「無 BOSS 檢查的秒殺入口」',
  '',
  '【實作位置】',
  '・index.html (line ~12133) — BOSS_NAMES.has → .includes',
  '・index.html (line ~18247) — 死神龍王登場收割加 BOSS 判定',
  '・index.html (line ~27770) — 吸血鬼靈魂收割加 BOSS 判定',
  '・index.html (line ~30317) — deathmark 觸發加 BOSS 判定(關鍵修補)',
  '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.13',
] },
