// ═══════════════════════════════════════════════════════════════════
// game_changelog.js 補丁 v3.5.8 + v3.5.9 + v3.5.10 + v3.5.11 + v3.5.12
// 把以下「五個」物件依時間從新到舊加到 GAME_CHANGELOG 陣列最前面
//   → v3.5.12 物件放最前面(最新)
//   → v3.5.11 物件放第二個
//   → v3.5.10 物件放第三個
//   → v3.5.9 物件放第四個
//   → v3.5.8 物件放第五個(原本漏寫,跟這幾個版本一起補)
// ═══════════════════════════════════════════════════════════════════

{ ver:'v3.5.12', brief:[
  '📲 修補 iPad 玩家「按了加入主畫面卻沒出現桌面圖示」的 BUG',
  '⚠ iPad 上用 Chrome/Firefox/Edge 開啟時,自動提示玩家改用 Safari 並提供複製網址鈕',
  '✅ 已加入主畫面的玩家再點下載按鈕時,改顯示「您已從主畫面圖示開啟」提示',
], items:[
  '【BUG:iPad 按「加入主畫面」沒出現桌面圖示】',
  '・症狀(老師 2026/5/22 回報):管理員同意下載權限後,玩家按「下載安裝完整遊戲」按鈕,',
  '         照引導步驟在 iPad 上「加入主畫面」,但桌面沒出現遊戲圖示',
  '・根因 1:apple-touch-icon meta 指向本地相對路徑 icon-180.png / icon-167.png 等,',
  '         但 PWA Service Worker 已被 v3.4.15 緊急止血停用(_PWA_DISABLED=true),',
  '         這些本地 icon 檔可能根本沒上傳到 GitHub Pages → iOS 抓不到圖示 →',
  '         部分 iOS 版本直接不建立桌面圖示',
  '・根因 2:玩家可能用 iOS 上的 Chrome / Firefox / Edge 開啟,這些瀏覽器在 iOS 上',
  '         「加入主畫面」只能建立「網頁捷徑」,完全不會建立 PWA 圖示',
  '         (iOS 政策只允許 Safari 建立 PWA)',
  '',
  '【修法 1:apple-touch-icon 改用 GitHub 上 100% 存在的圖】',
  '・index.html (line 5036-5040)所有 apple-touch-icon 改用絕對 URL,指向遊戲封面圖',
  '   (https://github.com/clarebox123jp-art/-/raw/main/遊戲封面.png)',
  '・這張圖在 line 5048 的 apple-touch-startup-image 已驗證可用',
  '・原本本地相對路徑 icon 改為註解保留,SW 重啟後可一鍵恢復',
  '・效果:iPad 加入主畫面時 iOS 必能抓到圖示,桌面圖示一定會出現',
  '',
  '【修法 2:_showPwaGuide 偵測非 Safari iOS 瀏覽器並提示】',
  '・index.html (line ~68820)新增 isNonSafariOnIOS 判定',
  '・iPad/iPhone 上若是 Chrome (CriOS) / Firefox (FxiOS) / Edge (EdgiOS),',
  '   引導視窗最上方顯示橘色警告框:',
  '   「⚠ 請改用 Safari 開啟此頁面!」',
  '   「iOS 規定只有 Safari 可以正確加入主畫面成為 App 圖示」',
  '   「在 Chrome 中加入主畫面只能建立網頁捷徑,圖示可能完全不出現!」',
  '   「請複製網址 → 關閉本瀏覽器 → 用 Safari 開啟後再來」',
  '・附「📋 複製網址」按鈕,點下自動 copy 當前 URL 到剪貼簿',
  '・步驟區也加上補充說明「Chrome iOS 只會建立捷徑,不是完整 PWA」',
  '',
  '【修法 3:已安裝 PWA 玩家再按時的友善提示】',
  '・_showPwaGuide 開頭新增 standalone 模式偵測',
  '   (window.matchMedia(\'(display-mode: standalone)\').matches 或 navigator.standalone)',
  '・若玩家已從主畫面圖示開啟遊戲,顯示 toast:',
  '   「✅ 您已經是從主畫面圖示開啟,無須再次安裝!」',
  '・避免重複按按鈕沒反應的疑惑',
  '',
  '【實作位置】',
  '・index.html (line 5024-5051) — apple-touch-icon 全部改用 GitHub 絕對 URL',
  '・index.html (line ~68820) — _showPwaGuide 加 isNonSafariOnIOS 判定 + 警告框',
  '・index.html (line ~68815) — _showPwaGuide 加 standalone 模式偵測',
  '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.12',
  '',
  '【部署提醒】',
  '・sw.js 的 SW_VERSION 需手動同步升到 v3.5.12 才能觸發強制更新',
  '・本次只修補了「加入主畫面成不成功」的問題;真正的「下載讀條安裝」要等 PWA SW 解除',
  '   緊急止血(v3.4.15)+ jsDelivr CDN 驗證完成才能恢復',
] },

{ ver:'v3.5.11', brief:[
  '🗾 日本關卡介紹的「獲得隨機新英雄(?)」名單修正:只有大天狗、酒吞童子、玉藻前、巫女 4 位',
], items:[
  '【改動:日本關英雄清單獨立池】',
  '・舊版(v3.5.10):? 鈕只支援貓空關,日本關沒有 ? 鈕,或誤用貓空池',
  '・新版(v3.5.11):重構成依關卡 key(maokong/japan)分別查英雄池',
  '・日本關固定 4 位:大天狗、酒吞童子、玉藻前、巫女(老師指定)',
  '・腳註說明:「大天狗 / 酒吞童子 / 玉藻前」分別對應三條 BOSS 路線通關獎勵;「巫女」為集齊三神器、擊敗八岐大蛇後的特殊解鎖獎勵',
  '',
  '【實作架構】',
  '・新函式 _advGetHeroPoolForStage(stageKey) — 中央化查池邏輯,maokong/japan 各回各的池',
  '・原 _showMaokongHeroListModal 改名 _showStageHeroListModal(stageKey),共用同一個 modal 函式',
  '・rewards 渲染時 ? 鈕的 onclick 改傳 stageKey 參數',
  '・舊名 _showMaokongHeroListModal 保留為相容 shim,內部轉呼新函式',
  '・台灣關 / 世界 BOSS 等其他關卡:_advGetHeroPoolForStage 回 null,不渲染 ? 鈕(維持原樣)',
  '',
  '【實作位置】',
  '・index.html (line ~42985) — rewards 渲染改用 _advGetHeroPoolForStage + 傳 stageKey 給 modal',
  '・index.html (line ~54512) — 新增 _advGetHeroPoolForStage 函式',
  '・index.html (line ~54560) — 新增 _showStageHeroListModal 函式(從 _showMaokongHeroListModal 重構)',
  '・index.html (line ~54725) — 保留 _showMaokongHeroListModal 相容 shim',
  '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.11',
] },

{ ver:'v3.5.10', brief:[
  '📱 iPad 與手機版「冒險關卡介紹」右側視窗下方加高,貼近底部按鈕(PC 不變)',
  '🦸 貓空關「獲得隨機新英雄」獎勵旁加「(已全收錄 / 尚有 N 位未相遇)」標示',
  '❓ 旁邊加 ? 鈕,點開可看所有貓空可加入英雄清單(已收錄/未相遇分組)',
], items:[
  '【改動 1:iPad/手機版冒險關卡介紹右側視窗加高】',
  '・舊版:_mobile-nav-active 狀態下 #adv-info-window 高度 760px;iPad 因被排除而完全沒設高,看起來短',
  '・新版:_mobile-nav-active(手機)→ 920px(+21%);iPad 透過 @media (pointer:coarse) 補一份規則',
  '・@media 用 (pointer:coarse) and (max-width:1366px) and (min-width:601px) 鎖定平板尺寸',
  '・PC 是 (hover:hover)(pointer:fine),不會吃到這條規則,維持原貌',
  '・配套:#adv-right-panel min-height 880 → 1040,padding-bottom 維持 60px',
  '',
  '【改動 2:貓空關介紹「獲得隨機新英雄」加收錄狀態】',
  '・在獎勵清單渲染時偵測 icon === \'🦸\',自動拼接收錄狀態文字',
  '・已全收錄:綠色「(已全收錄)」',
  '・尚有缺漏:橘色「(尚有 N 位未相遇的英雄)」',
  '・名單範圍:ADV_UNLOCKABLE_HEROES 31 個 - 商店肖像 8 個 - 事件限定 3 個 = 20 個',
  '',
  '【改動 3:點 ? 鈕開英雄清單視窗】',
  '・新函式:_showMaokongHeroListModal()(v3.5.11 重構為 _showStageHeroListModal)',
  '・顯示元素:標題列 + 收錄進度條(綠色漸層) + 已收錄分組 + 未收錄分組 + 說明腳註',
  '・已收錄英雄:綠色邊框 + 「✓ 已收錄」徽章 + 彩色頭像',
  '・未收錄英雄:灰色邊框 + 「? 未相遇」徽章 + 灰階頭像 + 半透明',
  '・響應式網格:grid-template-columns:repeat(auto-fill,minmax(110px,1fr)) 自動排列',
  '・腳註說明清楚標示:不含商店肖像 8 位、不含事件限定 3 位(小力/幼兒園小孩/巫女)',
  '',
  '【實作位置】',
  '・index.html (line ~42985) — adv-rewards-list 渲染加收錄狀態 + ? 鈕',
  '・index.html (line ~54510) — 新增 _showMaokongHeroListModal 函式',
  '・index.html (line ~76735) — _mobile-nav-active 高度規則 760→920 / 880→1040',
  '・index.html (line ~76753) — 新增 @media (pointer:coarse) 規則供 iPad 套用',
  '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.10',
] },

{ ver:'v3.5.9', brief:[
  '🐲 維蘇威火山龍王平衡調整:S1 業火灼燒 c:4→5、傷害 100%→150%;爆發 90%→95%',
  '🛡 維蘇威護盾改成依「回合數」觸發(第 5/9/13/17 回合),取代原 HP% 機制',
  '💥 全隊聯手爆發 5000 傷害無視護盾打穿,鼓勵團隊答題合作',
  '⛩ 巫女天賦「祝禱」調整:每回合只附加 1 名友方(不再隨 Lv 增加人數)',
  '🌟 占星師天賦「星語」強化:能量補充改為 +3,機率 70%+5%/級(Lv4 達 90%)',
  '🛡 戰鬥定型文新增「先破盾」+ 可收起/展開定型文列(跨場記憶)',
  '💬 答題期間非答題玩家定型文 UI 浮在問題視窗之上,可即時討論',
], items:[
  '【改動 1:維蘇威 S1「業火灼燒」強化】',
  '・能量消耗:4 → 5(難釋放但更值得)',
  '・傷害倍率:特技 100% → 150%(基礎 sp=50 → 一發約 75 點全體傷,搭配燃燒 2 回合)',
  '・對應 HERO_DB 文案 + 實作公式 + bannerFX 已同步更新',
  '',
  '【改動 2:維蘇威爆發「天崩之炎」強化】',
  '・全體當前 HP 傷害比例:90% → 95%(更具毀滅性,連 BOSS 倒下都更接近一擊定生死)',
  '・其他效果(無視有利狀態 / 強力燃燒 3 回合 / 1 名強力暈眩+易傷)維持不變',
  '・對應 BURST_DB 文案同步更新',
  '',
  '【改動 3:維蘇威護盾觸發機制改版】',
  '・舊版(v3.1.2):依 BOSS HP% 觸發(80%/60%/40%/20%/1%) — 輸出強的隊跳過階段、輸出弱的看不到後期護盾',
  '・新版(v3.5.9):每場戰鬥固定在「第 5/9/13/17 回合」啟動,共 4 道護盾',
  '・所有隊伍體驗一致,玩家可以根據回合數預先規劃元素破盾節奏',
  '',
  '【改動 4:全隊聯手爆發 5000 無視護盾】',
  '・觸發條件:全隊累積答對 5 / 10 / 15 / 20 題(每場最多 4 次)',
  '・這個 5000 傷害不走 doDmg、不走 _wbApplyBossDmgCap → 不被護盾減傷 80% 影響',
  '・正式定名為「全隊聯手爆發」並補上明確 log/視覺提示「(穿透元素護盾!)」',
  '',
  '【改動 5:巫女天賦「祝禱」調整】',
  '・舊版:Lv0=1 人 / Lv1=1 人 / Lv2=2 人 / Lv3=3 人 / Lv4+=4 人',
  '・新版:固定 1 人(有利狀態最少的友方),不再隨 Lv 增加人數',
  '・每人附加的「狀態數量」維持原規則:Lv0~4 = 1 個,Lv5(MAX) = 2 個',
  '・能量恢復機率規則維持不變:50% + 10%/級,Lv5 達 100%',
  '',
  '【改動 6:占星師天賦「星語」強化】',
  '・舊版:60% + 4%/級 機率補 1 能量 (Lv5 = 80%)',
  '・新版:70% + 5%/級 機率補 3 能量 (Lv0=70/Lv1=75/Lv2=80/Lv3=85/Lv4+=90%)',
  '',
  '【改動 7:戰鬥定型文新增「先破盾」按鈕】',
  '・位置:在「控住王 🌀」與「太棒啦 🔥」之間,藍色盾牌圖示「🛡 先破盾」',
  '・用途:提醒隊友「BOSS 護盾已啟動,先用對應元素英雄削層再輸出」',
  '',
  '【改動 8:定型文列「收起/展開」功能】',
  '・最左邊新增「⏷ 收起」鈕,點下整列收起成左上角小圓鈕「💬 發言」',
  '・狀態用 localStorage(key=lxps_wb_emoji_bar_collapsed)跨場記憶',
  '',
  '【改動 9:答題期間非答題玩家 UI 提升】',
  '・答題玩家思考時,其他三位玩家的定型文 UI 自動浮到問題視窗之上(z-index 10950)',
  '・讓非答題玩家可以即時用「A/B/C/D」討論按鈕或定型文鼓勵答題者',
  '・自動偵測:_wbAssignedQuizSlot 設值且自己不是答題者時觸發,500ms 輪詢更新',
  '',
  '【CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.9】',
] },

{ ver:'v3.5.8', brief:[
  '🔧 修補世界 BOSS 戰 P2 client 回合無限循環(Firestore 樂觀鎖衝突)',
  '📊 修補房主端「本場總傷」一直顯示 0',
  '🐲 維蘇威 BOSS 能力卡片速度顯示 25 → 15(與實際戰鬥值一致)',
], items:[
  '【BUG #1:P2 client 玩家回合無限循環】',
  '・症狀:電腦繪圖師(P2 client)的回合一直結束不了,15 秒後 watchdog 觸發,',
  '         玩家送 _client_stuck_resync 給房主,房主重發 sync 仍卡住,console 看到 400 Bad Request',
  '・根因:Firestore 多人同時寫 worldBossRooms 文件撞到樂觀鎖衝突(failed-precondition),',
  '         hostPushBattleState 沒有重試 → 一次失敗就丟下,client 永遠收不到新 sync。',
  '         (v3.5.1 已修了 client 端 sendAction 重試,但 host 端的 hostPushBattleState 漏修)',
  '・修法:hostPushBattleState 加 3 次重試,指數退避 300/600/1200ms + 0~200ms 隨機抖動',
  '',
  '【BUG #2:房主端「本場總傷」一直 0】',
  '・症狀:房主造成傷害,但左上「本場總傷」一直顯示 0',
  '・根因:v3.5.3 把組隊模式新版 UI 元素 ID 改成 wb-cur-dmg-display,client 端 onRoomUpdate 已改成兩 ID 兜底,',
  '         但 host 端的 addContribution 還停留在舊 ID wb-solo-cur-dmg-display → 找不到該元素 → 永遠不更新',
  '・修法:addContribution 改成找新舊 ID 兜底,跟 client 端與 fake _wbNet 處理一致',
  '',
  '【BUG #3:維蘇威 BOSS 能力卡片速度欄位不一致】',
  '・卡片顯示 25,但 HERO_DB 實際戰鬥用 15 → 玩家看到的跟實際不同',
  '・修法:卡片數字 25 → 15(與 HERO_DB / 戰鬥邏輯 / 其他 UI 元件一致)',
  '',
  '【CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.8】',
] },
