// ════════════════════════════════════════════════════════════════════
// game_changelog.js — v3.5.32 ~ v3.5.53 新增條目
// 把以下條目加到 GAME_CHANGELOG 陣列的最前面
// 順序由新到舊:v3.5.53 → v3.5.52 → v3.5.51 → v3.5.50 → v3.5.49 → v3.5.48 → ...
// (v3.5.33 跳號:中途整合測試用過,未發布)
// ════════════════════════════════════════════════════════════════════

  { ver:'v3.5.53', brief:[
    '🛡 全遊戲按鈕冷卻系統大上線!防止亂按造成 Firebase 寫入爆炸',
    '⏰ 商店買賣、至寶投資、裝/卸至寶、預設陣容、加好友、立即同步雲端全加冷卻',
    '📊 冒險次數寫雲端從「每場 +1」改為「每小時最多 +1」,大幅減少 Firebase 寫入',
    '☁ 立即同步雲端每日上限 50 → 30 次(更保守,正常玩家用不到 5 次)',
  ], items:[
    '【背景:為什麼要做這個?】',
    '・系統全盤檢查發現 227 個 Firebase 寫入點,其中很多按鈕沒有冷卻保護',
    '・玩家如果亂按可能 1 秒寫雲端 20+ 次,容易造成 Firebase 配額爆掉',
    '・Firebase Spark 免費方案每日 20K 寫入,29 位玩家若都亂按可能撐不到中午',
    '【新增統一冷卻工具 _btnCooldown】',
    '・全域工具 window._btnCooldown(key, ms) — 統一管理所有冷卻',
    '・回 true 代表允許執行、回 false 代表冷卻中已擋下並彈出 toast 提示',
    '・各動作可自訂冷卻時間,根據風險程度設定',
    '【冷卻決策表】',
    '・商店買賣(B-1):0.8 秒 — 防玩家連點寫雲端爆炸',
    '・至寶經驗卷軸(B-2):0.3 秒 — 短冷卻,投資多張是合理操作',
    '・裝/卸至寶(B-3):1 秒 — 換裝是低頻操作',
    '・預設陣容儲存/刪除(B-4):2 秒 — 不該連續做',
    '・加好友(C-1):3 秒 — 加好友本來就慢動作',
    '・冒險次數寫雲端(E-1):每小時最多 +1 — 老師指示「不重要,降到極低頻率」',
    '・立即同步雲端(E-2):每日 30 次(原 50 次)— 更保守的配額',
    '【E-1 冒險次數冷卻特別說明】',
    '・原本:玩家每按「整裝出發」就寫雲端 +1,1 分鐘可累積 20+ 次寫入',
    '・新版:用 localStorage 記錄上次寫雲端時間戳,1 小時內跳過寫入只 console.log',
    '・好處:Firebase 寫入減少 95%+,統計只是「最近一小時內有沒有玩家進冒險」的粒度',
    '・玩家無感知:UI 不會出現任何提示,純後端冷卻',
    '【E-2 立即同步雲端配額降低】',
    '・每日上限從 50 次 → 30 次',
    '・觸發訊息文案同步調整',
    '・每次按下仍維持 10 秒間隔(沒變動)',
    '【未加冷卻的點(不需加,有其他保護)】',
    '・能力素質投資、技能升級、爆發升級 — 有「確認視窗」這層保護',
    '・召喚 1 次 / 10 連召喚 — 動畫期間 btn.disabled 鎖定',
    '・物品使用(經驗書/果實等)— 有確認視窗 + 物品總數有限',
    '・戰鬥中行動 — 戰鬥流程節流',
    '【實作位置】',
    '・統一冷卻工具 _btnCooldown:index.html line ~56961',
    '・E-1 冒險次數冷卻:index.html line ~1413 (_fbIncrementAdventureCount)',
    '・E-2 立即同步 30 次:index.html line ~57002',
    '・B-1 商店買賣:line ~63408 / ~63471',
    '・B-2 至寶卷軸:line ~40679',
    '・B-3 裝/卸至寶:line ~67034 / ~67061',
    '・B-4 預設陣容:line ~64163 / ~64269',
    '・C-1 加好友:line ~71197 / ~71276',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.53',
  ] },

  { ver:'v3.5.52', brief:[
    '🐛 修「更新日誌按了等很久都沒出現視窗」的 BUG',
    '🔍 「檢查我的進度」和「檢查遊戲版本」的「?」說明視窗放大 200%,字級更清楚',
    '⏰ 更新日誌載入加 8 秒逾時保護,不再無聲卡死',
    '💡 載入失敗會跳明確訊息(含目前版本、重試按鈕),不再用簡陋 alert',
  ], items:[
    '【老師回報】',
    '・點「📋 更新日誌」按鈕後,只看到「⏳ 更新日誌載入中…」訊息',
    '・等很久(超過 10 秒以上)都沒出現實際視窗和內容',
    '・「檢查我的進度」和「檢查遊戲版本」的「?」說明視窗字太小,看不清楚',
    '【根因分析】',
    '・原 _ensureChangelogLoaded 邏輯只依賴一個觸發點:game_changelog.js 結尾呼叫 window._onChangelogReady()',
    '・如果線上 game_changelog.js 因為任何原因沒呼叫(忘了寫、CDN 不同步、script 載入但執行錯誤),',
    '  就會永遠卡在「載入中」狀態,沒有逾時、沒有錯誤訊息',
    '・原來的「載入失敗」alert 訊息也很簡略,玩家不知道是網路問題還是檔案問題',
    '【修補:四層保險載入機制】',
    '・保險 1:script.onload 事件 — 瀏覽器下載完成 + 執行完畢時觸發,直接檢查 GAME_CHANGELOG 是否定義',
    '・保險 2:8 秒逾時保護 — 超過 8 秒未完成 → 標記 failed 並彈出明確錯誤視窗',
    '・保險 3:輪詢備援 — 每 200ms 檢查一次 GAME_CHANGELOG 是否存在,共輪詢 40 次',
    '・保險 4:_onChangelogReady 仍保留 — 線上版 game_changelog.js 若有呼叫仍走原路徑',
    '・破快取參數從 v=20260516 → v=20260523',
    '【載入中視窗強化】',
    '・原本只顯示「⏳ 更新日誌載入中…」一句',
    '・新版加大 + 加倒數秒數:「最多等 8 秒」每秒遞減,讓玩家知道在等什麼、要等多久',
    '・點背景可主動關閉(不必傻等)',
    '【載入失敗視窗強化】',
    '・原本只彈簡陋 browser alert「更新日誌載入失敗,請檢查網路後重試」',
    '・新版改為紅色 modal:含可能原因、解決方法、目前遊戲版本、🔄 重試按鈕、關閉按鈕',
    '【說明視窗放大 200%】',
    '・檢查我的進度的「?」說明:max-width 520→900px、所有字級放大 1.5~2 倍',
    '・檢查遊戲版本的「?」說明:同步放大,跟綠色版視覺一致',
    '・按鈕 padding 22px / 字級 28px,iPad 上點起來很容易',
    '【實作位置】',
    '・_ensureChangelogLoaded 四層保險重寫:index.html line ~79160',
    '・openChangelogPanel 載入中倒數:index.html line ~69824',
    '・_showChangelogLoadFailedDialog 新函式:index.html line ~69989',
    '・_showManualCheckHelp 放大:index.html line ~57232',
    '・_showVersionCheckHelp 放大:index.html line ~57481',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.52',
  ] },

  { ver:'v3.5.51', brief:[
    '🐛 修「火柴人/青炎龍王技能完全無效只能普攻」的大 BUG',
    '🔥 火柴人 4 個技能 + 青炎龍王 4 個技能全部補完整實作,玩家點下去真的會有效果了',
    '⚡ 確認技能升級也都依公式正確套用(主傷害 +5%、追加機率 +3% 等)',
  ], items:[
    '【玩家回報】',
    '・火柴人在戰鬥中,不管按 S1「燃燒的火柴盒」還是 S2「保持正能量」,都沒任何反應',
    '・只能用普通攻擊,技能像被禁用一樣',
    '・青炎龍王也有同樣問題',
    '【根因分析(老師血淚教訓)】',
    '・v3.5.49 第一次加入這兩位英雄時,把 S1/S2 主動技能實作「錯放」到 aiUseSkill 函式裡',
    '・aiUseSkill 是給 AI/NPC 用技能的,不是給玩家用的',
    '・玩家點技能走的是 execSkill 函式,裡面找不到「燃燒的火柴盒」「青炎爆破」等分支,',
    '  直接掉到「未識別技能」兜底 → 完全沒任何效果',
    '・更慘的是,aiUseSkill 內這四段還用了 setPending(玩家選目標彈窗),AI 根本不能這樣寫',
    '【修補內容】',
    '・在 execSkill 內補上完整的玩家版實作(8 個技能效果):',
    '   - 火柴人 S1「燃燒的火柴盒」:特技 200% 火屬性 + 60% 機率追加,必中無視有利',
    '   - 火柴人 S2「保持正能量」:全體治療 125%(可復活)+ 全體迴避 30% 兩回合',
    '   - 青炎龍王 S1「青炎爆破」:自損 25% HP,全敵特技 100%+HP 20% 火傷害 + 扣對手 4 能量',
    '   - 青炎龍王 S2「炎之視線」:開啟反擊狀態,對手用技能時 65% 反擊火傷害並燃燒',
    '・修正 aiUseSkill 內的錯版本:移除 setPending、endAction、return,改用 t/enemies/allies 自動選目標',
    '・天賦「以火還火」「藍焰守護」+ 爆發「燃燒自己,照亮別人」「青炎之舞」維持 v3.5.49 已正確的版本',
    '【新訂鐵律 1.54】',
    '・以後新增任何英雄,必須同時補完 execSkill(玩家版)+ aiUseSkill(AI 版)兩份實作',
    '・寫完後必須親自跑一場戰鬥確認技能真的有效果再交付',
    '・這是 LXPSGAME 史上第一次「技能完全無效」的回報,絕不能再發生',
    '【實作位置】',
    '・execSkill 新增 4 段技能:index.html line ~29890(戰場交易後、未識別技能兜底前)',
    '・aiUseSkill 修正 4 段:index.html line ~34602(原 v3.5.49 錯位的版本就地修正)',
    '・天賦「以火還火」鉤子:line ~23030(維持 v3.5.49)',
    '・天賦「藍焰守護」、爆發實作:維持 v3.5.49(本來就在正確位置)',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.51',
  ] },

  { ver:'v3.5.50', brief:[
    '🔄 關卡頁新增「檢查遊戲版本」按鈕(藍色),可隨時主動確認自己版本是不是最新',
    '📋 「檢查我的進度」按鈕原本一顆,現在拆成兩顆:左=檢查進度、右=檢查遊戲版本',
    '✅ 不是最新版時可一鍵重新整理套用,並查看更新日誌了解這次改了什麼',
  ], items:[
    '【為什麼要這個?】',
    '・原本只有自動偵測(90 秒輪詢)+ 金色 banner 提示玩家有新版',
    '・但有時候老師說「我剛修好上線了」,學生會想主動確認是不是套到自己畫面了',
    '・現在多一顆主動檢查按鈕,玩家可自己掌控更新時機 + 馬上看更新日誌了解差異',
    '【三種結果情境】',
    '・✅ 已是最新版:藍框 + 顯示大字版本號 + 「📋 查看更新日誌」按鈕',
    '・🎉 有新版本:金框 + 脈動光暈 + 顯示「目前版本 ▼ 最新版本」對比',
    '  - 三選一:「📋 查看更新日誌」「🔄 立即重新整理」「稍後再說」',
    '  - 立即重新整理會呼叫既有 _refreshForUpdate,戰鬥中會跳二次確認',
    '・⚠️ 無法連線伺服器:紅框 + 提示檢查網路',
    '【新增「?」說明視窗】',
    '・跟綠色「檢查我的進度」的「?」同設計風格(藍色配色)',
    '・說明跟「檢查我的進度」的差異:對比遊戲程式 vs 對比玩家資料',
    '・提醒戰鬥中重新整理會中斷戰鬥',
    '【實作位置】',
    '・按鈕區拆分:index.html line ~6711(四個按鈕並排:檢查進度+? / 檢查版本+?)',
    '・_manualCheckGameVersion 主動檢查函式:index.html line ~57187',
    '・_showVersionCheckResultDialog 結果彈窗(三種狀態):index.html line ~57248',
    '・_showVersionCheckHelp 說明視窗:index.html line ~57370',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.50',
  ] },

  { ver:'v3.5.49', brief:[
    '💾 整裝完畢出發前,如果偵測到「全新陣容」會主動詢問是否儲存為預設陣容',
    '🔥 新增第二位學生設計英雄「青炎龍王」(5 年 3 班蔣同學設計)',
    '📋 移除技能替換頁的「✦ 自動推薦替換技能」按鈕,改由更聰明的儲存陣容流程取代',
    '⚠️ 注意:本版的火柴人/青炎龍王 S1/S2 技能有 BUG(放錯函式),已在 v3.5.51 修補',
  ], items:[
    '【整裝完畢→儲存陣容流程】',
    '・編組好英雄、選好元素、配好替換技能後,按「🗺 整裝完畢,冒險出發」',
    '・系統自動比對當前陣容(英雄/元素/替換技能)與已儲存的 5 個預設欄位',
    '・若完全相符(已存過) → 直接進入戰鬥',
    '・若不相符(全新陣容) → 跳藍紫色彈窗詢問:',
    '  - 💾 儲存為預設陣容 → 開啟欄位選擇 → 命名 → 完成後自動接續開戰',
    '  - 不儲存,直接出發 → 直接進戰鬥',
    '・彈窗底部有「今天不再顯示此提示」勾選框(localStorage 紀錄當天日期)',
    '・只在冒險模式啟用,鬥技場不打擾',
    '【新增英雄:青炎龍王】',
    '・5 年 3 班蔣同學設計,LXPSGAME 第二位 5 年 3 班學生設計師',
    '・能力:HP 60 / 攻擊 9 / 特技 20 / 速度 11 = 100',
    '・天賦「藍焰守護」:存活時友方 HP < 20% 自動附加特技 100% 護盾 2 回合(不可堆疊)',
    '・S1「青炎爆破」:自損 25% HP,全敵特技 100%+HP 20% 火傷害(上限 Lv×10)+ 扣對手 4 能量',
    '・S2「炎之視線」:對手用技能時 65% 機率反擊特技 100% 火傷害 + 燃燒 2 回合',
    '・爆發「青炎之舞」:全敵特技 200% 火傷害 + 30% HP 復活全體倒下隊友 + 全友迴避 2 回合',
    '・人物設定:「孩子,別怕——青藍之火,只焚邪佞,只暖善良。」',
    '【移除自動推薦替換技能按鈕】',
    '・原本玩家可以按「✦ 自動推薦替換技能」讓系統幫忙挑,但很多玩家不會主動用',
    '・改成由「整裝完畢」按鈕主動詢問儲存預設陣容,讓常用陣容能快速套用',
    '【實作位置】',
    '・_maybePromptSaveAsPresetThenStart:index.html line ~16490',
    '・_isCurrentTeamMatchingAnyPreset:line ~16511',
    '・_showSaveAsPresetPrompt:line ~16546',
    '・_confirmSavePreset 結尾接 callback:line ~63727',
    '・_closePresetOv 接住取消流程:line ~64018',
    '・青炎龍王 hero_db.js 18 處插入點(同火柴人)',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.49',
  ] },

  { ver:'v3.5.48', brief:[
    '🔧 修「資料還在路上!請確認復原」視窗每次開遊戲都跳的 BUG(其實多數是誤觸發)',
    '💎 修救援對比視窗「右邊雲端至寶永遠顯示 0 件」的 BUG(看錯欄位)',
    '🛡 加合理性檢查:本地英雄總等級 ≥50 一律當資料正常,不再誤判空殼',
    '🛠 管理員 console 指令區塊改用紫色框 + 醒目標籤,明確標示「學生看不到這段」',
  ], items:[
    '【BUG 1:救援彈窗每次開遊戲都跳】',
    '・老師截圖證據:本地「等級總和 3001、最高巫女 Lv.40」明明資料正常,卻說「解鎖角色 0 位是空殼」',
    '・根因:_getLocalSummary() 用 typeof _unlockedHeroes !== \'undefined\' 判斷,但',
    '       _unlockedHeroes 這個全域變數根本沒有被宣告(整個程式碼裡 grep 不到 let/var/const)',
    '・→ typeof 永遠是 undefined → unlocked 永遠回 0 → 觸發「英雄解鎖數異常」誤判',
    '・修法:解鎖數三源取最大值 — advGetUnlockedHeroes() / _heroLevels 推導 / _unlockedHeroes fallback',
    '・加合理性檢查:本地 totalLv >= 50 或 maxLv >= 5 → 一律視為「資料正常」,跳過異常偵測',
    '       (有等級代表資料一定有載入,不可能是空殼)',
    '・冷卻策略改用 sessionStorage:同 session 內彈過就不再彈,要重新整理才會重新檢查',
    '・對話框「稍後再說」按鈕文案改成「同 session 內不再跳」更貼近實際行為',
    '【BUG 2:右邊雲端版本「解鎖至寶 0 件」(根本不對)】',
    '・根因:_extractDataSummaryForCompare 函式看錯欄位',
    '       舊版:Array.isArray(data.treasures) 看陣列(這是戰鬥中至寶槽快照)',
    '       正確:data.taiwanTreasureData 物件(玩家擁有的至寶清單,格式 {id:{lv,exp,equippedTo}})',
    '・修法:重寫至寶計算,三層來源合併:',
    '       ① data.taiwanTreasureData 物件(主要來源)→ 從 TAIWAN_TREASURES 抓 name/icon',
    '       ② data.japanProgress.treasures(日本三神器 boolean)→ 大天狗/酒吞童子/玉藻前',
    '       ③ data.treasures(舊欄位 fallback,避免破壞既有相容性)',
    '・本地 _extractLocalLiveSummaryForCompare 同步修(舊版只看 _advTreasures 戰鬥槽,改用 _taiwanTreasureData)',
    '【BUG 3:管理員 console 指令文字看起來像給所有玩家看的】',
    '・老師懷疑:全玩家都看得到 _adminPeekCloud / _adminForceReloadFromCloud 文字嗎?',
    '・確認:程式碼邏輯 (_isAdmin ? "..." : "") 是對的,只有管理員(email 白名單)看得到',
    '・改善:把這段獨立成紫色框 + 標籤「🛠 管理員專用區塊(學生看不到這段)」,',
    '       讓老師一眼就知道「啊我是管理員測試所以看到這段,學生不會看到」',
    '【實作位置】',
    '・_getLocalSummary 修正:index.html line ~74941',
    '・_checkMismatch 合理性檢查:index.html line ~74980',
    '・session 冷卻:index.html line ~74937(SESSION_KEY)',
    '・_extractDataSummaryForCompare 至寶大修:index.html line ~75444',
    '・_extractLocalLiveSummaryForCompare 同步修:index.html line ~75554',
    '・管理員區塊醒目化:index.html line ~75052',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.48',
  ] },

  { ver:'v3.5.47', brief:[
    '🎯 大整合版本:把過去幾次零散的改動全部到位 — GM 後台改版 + 對比表 + 版本通知 + iPad 捲動',
    '📱 iPad 版關卡頁右側介紹底下的「獎勵」終於可以滑動看到了!以前被蓋住的內容現在可以捲上來',
    '🛠 GM 後台 PC 版放大 200% 並置中,功能依重要性重排,標題改為「遊戲管理員(GM)專用功能選單」',
    '📲 第一次看到下載按鈕亮起時,自動跳出「安裝版 vs 網頁版」對比表,讓玩家自己決定',
    '✨ 老師更新程式碼 90 秒內,玩家畫面會跳金色 banner + 右上角按鈕亮起改成「重新整理」',
  ], items:[
    '【📱 iPad 關卡頁右側介紹可捲動了】',
    '・老師回報:iPad 版選關卡時,右邊介紹底下的「🎁 獎勵」項目常被蓋住或超出畫面',
    '・問題尤其在「🦸 獲得隨機新英雄」項目,玩家想確認還缺哪幾隻英雄沒收錄,卻滑不到',
    '・根因:v3.5.10 把 #adv-info-window 高度從 760→920 但沒設 overflow-y → 內容超出直接被裁掉',
    '・修法:body._mobile-nav-active + (pointer:coarse,max-width:1366px) 兩條 iPad 規則都加上',
    '   - overflow-y: auto(啟用垂直捲動)',
    '   - -webkit-overflow-scrolling: touch(iOS 慣性捲動)',
    '   - scroll-padding-bottom: 20px(底部留緩衝)',
    '   - padding-bottom: 24px(獎勵不貼邊)',
    '   - 漂亮的金色 webkit-scrollbar(讓玩家看到「還有內容」)',
    '・PC 版完全不受影響(這兩條規則只匹配 iPad)',
    '【🛠 GM 後台改版 — PC 版放大 200%】',
    '・面板標題從「人數統計管理工具」→「🛠️ 遊戲管理員(GM)專用功能選單」',
    '・新增 @media (min-width:1024px) and (min-height:900px) 規則:',
    '   - 卡片寬度 560 → 1120 px,padding 32→56,字級 ×1.6~2 倍',
    '   - margin:0 auto 垂直水平置中',
    '・14 個區段依重要性 flex order 重排:',
    '   1.維修 2.GM公告 3.錯誤回報 4.Lv1救援 5.急救工具 6.補償 7.下載權限',
    '   8.可疑帳號 9.世界BOSS榜 10.解除冷卻 11.測試批次 12-14.統計類',
    '・7 個無 id 區段補上 _admin-XXX-section id',
    '・手機/筆電/小螢幕完全不影響(只在 PC 大螢幕觸發放大)',
    '【📲 安裝版 vs 網頁版 對比表彈窗】',
    '・新增 window._showInstallBenefitsDialog([forceShow]) 函式',
    '・10 列對比表:啟動速度/離線/流暢度/空間/下載時間/進度同步/更新方式/共用平板風險/桌面圖示/推薦情境',
    '・紅框警示:「共用平板的學生建議用網頁版」(避免帳號互相干擾)',
    '・兩顆按鈕:「⬇️ 立即下載安裝」/「🌐 現在用網頁版就好」',
    '・觸發時機:',
    '   ① 玩家第一次看到下載按鈕亮起時自動彈一次(localStorage 標記避免重複)',
    '   ② 下載按鈕旁「❓ 了解差異」連結隨時可手動點開',
    '【✨ 即時版本更新通知 — 從 5 分鐘改成 90 秒】',
    '・舊版:每 5 分鐘檢查,偵測到新版直接彈 modal 強制中斷遊戲',
    '・新版:每 90 秒檢查(老師更新後 1-2 分鐘就會通知到玩家)',
    '・偵測到新版三件事一次發生:',
    '   ① 跳金色 banner(類似 GM 公告):告知玩家先回關卡同步進度再重整',
    '   ② 右上角「🔄 重新開始」按鈕自動改名為「🔄 重新整理(套用新版本)」+ 金色脈動光暈',
    '   ③ PC 版按鈕左側出現「👉」搖擺動畫 30 秒(手機不顯示避免擋畫面)',
    '・按鈕 onclick 從 ctrlRestart() 改為 location.reload(true)',
    '・戰鬥中不強制中斷,玩家自己決定何時按重整',
    '・若戰鬥中按下,_customConfirm 會二次確認',
    '【知識幣倒退跳過(v3.5.46 保留)】',
    '・繼續保持「完全不擋知識幣倒退」— 老師指示:消費是玩家自己的選擇,不該擋',
    '・只看英雄三指標倒退(unlocked/maxLv/totalLv)',
    '【實作位置】',
    '・iPad 右側介紹捲動:index.html line ~78237-78310(兩條 iPad 規則加 overflow-y)',
    '・對比表函式:index.html line ~68009-68155',
    '・對比表自動觸發:index.html line ~67828(_updateDownloadAuthUI 內加守門)',
    '・了解差異按鈕:index.html line ~6386',
    '・版本通知系統:index.html line ~77891-78090(完整改寫)',
    '・GM 後台改動:admin_panel.js line ~89(PC 200% 規則) + ~169(flex order) + ~196(新標題)',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.47',
  ] },

  { ver:'v3.5.46', brief:[
    '🛡 雲端寫入保護策略調整:完全移除「知識幣大幅倒退」檢測',
    '💰 之前升級至寶/買召喚水晶/買知識卡時偶爾會被誤判為「資料倒退」而拒絕儲存',
    '✨ 現在只看英雄相關指標(解鎖數/最高等級/總等級),不再因知識幣消費而擋下存檔',
  ], items:[
    '【問題】v3.5.38 雖然把知識幣硬擋閾值放寬到 10 萬,但仍會擋到大消費',
    '・單次升級「玉山巔峰之盾」Lv5→Lv10 連扣可能超過 10 萬',
    '・召喚池十連扣 5 萬,連續抽兩次就破門',
    '・學生存夠 20 萬後一口氣全部投資英雄/裝備,合理消費但會被擋',
    '【根本原因】知識幣倒退跟「帳號被覆蓋」幾乎無關',
    '・99% 的知識幣大幅倒退都是玩家自己消費',
    '・即使「200,000 全敗光」也是玩家自己的選擇,系統不該擋下並搞丟存檔',
    '・真正的「帳號被別人覆蓋」訊號是英雄資料倒退(解鎖數變少、等級全部歸零)',
    '・知識幣只是噪音,移除它能大幅降低誤殺率',
    '【這次怎麼修?】',
    '・✨ _hardRegression 條件移除 coinsDelta <= -100000(完全不擋知識幣)',
    '・✨ _rejectReasons.push("知識幣大幅倒退...") 移除',
    '・✨ 「通過但留 log」的雜訊 console.log 移除(每次正常扣款都印 log 干擾 console)',
    '・✨ 註解更新為 v3.5.46,清楚記錄變更理由(下次有人看程式碼能立即理解)',
    '【保留的硬擋條件】',
    '・解鎖英雄倒退 >= 5 隻(這是真的「帳號被覆蓋」訊號)',
    '・最高英雄等級倒退 >= 5 級',
    '・總英雄等級倒退 >= 100 級',
    '・複合英雄倒退(unlocked -2 且 maxLv -3 等三種組合)',
    '【影響範圍】',
    '・玩家:不再因消費而被擋下儲存,UI 不再彈紅框「雲端寫入保護啟動」',
    '・老師:後台 BUG 回報應該大幅減少(消費被擋的 case 全部消失)',
    '・系統:Firestore 寫入次數可能略增(以前被擋下的會通過了),但屬合理範圍',
    '【實作位置】',
    '・index.html line ~966-1018(_fbSaveLive 健康度守門邏輯)',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.46',
  ] },

  { ver:'v3.5.45', brief:[
    '✂️ 程式碼大瘦身:管理員後台從 index.html 抽出為獨立檔案 admin_panel.js',
    '📦 玩家初次載入省 240 KB(學校網路約省 0.4 秒)',
    '🛠 老師按 Shift+F10 第一次開後台才會下載 admin_panel.js(之後從快取讀,瞬開)',
  ], items:[
    '【為什麼這樣改?】',
    '・管理員後台 _showAdminStatsPanel 函式長達 4,380 行 / 240 KB',
    '・但 100% 只有管理員會用到,玩家不會碰',
    '・以前每位玩家每次開遊戲都要載這 240 KB 死碼',
    '・抽出來後玩家根本不用下載,管理員第一次按 Shift+F10 才載一次',
    '【拆出來的內容】',
    '・整個 _showAdminStatsPanel 函式(含面板 UI HTML 模板 + 14 個區段的 JS 邏輯)',
    '・在 index.html 原位置改成 stub:呼叫時動態 fetch admin_panel.js,確保載入後再執行',
    '・lazy load 模式跟 game_changelog.js 一樣(已驗證可用)',
    '【效益】',
    '・index.html 大小:4,355 KB → 4,118 KB(省 5.4%)',
    '・玩家行為完全不變(他們本來就用不到後台,現在也碰不到 admin_panel.js)',
    '・管理員第一次按 Shift+F10:多 ~150ms 的網路時間(GitHub Pages CDN 速度)',
    '・管理員之後再按:跟以前一樣瞬開(瀏覽器快取已存)',
    '【技術細節】',
    '・admin_panel.js 是純 script(不是 ES module),透過 <script src> 動態插入',
    '・載入完會把 window._showAdminStatsPanelImpl 掛到 global',
    '・stub _showAdminStatsPanel() 內部 await window._ensureAdminPanelLoaded() 後才呼叫實作',
    '・首次載入有 console log:[admin_panel] 🔄 開始載入... → [admin_panel] ✅ 載入完成',
    '・破快取:admin_panel.js?v=YYYYMMDD,改動 admin_panel.js 後要更新這個版本參數',
    '【部署步驟】',
    '・上傳 admin_panel.js 到 GitHub 同層(跟 game_changelog.js / hero_db.js 並列)',
    '・上傳新版 index.html(_GAME_LOADED_VERSION 升為 v3.5.45)',
    '・部署後第一次按 Shift+F10:F12 → Network 應看到 admin_panel.js 200 OK',
    '・第二次按 Shift+F10:應從 disk cache 載入(不會再打 GitHub)',
    '【未來增肥防呆】',
    '・之後加 GM 工具請直接改 admin_panel.js,不再灌大 index.html',
    '・改 admin_panel.js 後記得改它最頂的版本標籤,並把 index.html stub 的 ?v=YYYYMMDD 升版',
    '・若 admin_panel.js 改太大也可以再拆(例如把學生補償工具獨立成 admin_compensation.js)',
    '【尚未拆出(可能未來再做)】',
    '・管理員測試/診斷 API:_adminPeekCloud / _adminForceReloadFromCloud 等',
    '  (這批跟 _grantRetroactiveMedalRewards 等玩家自動觸發的邏輯有耦合,要精細切片,本次先不拆)',
    '・PWA 模組 _lxpsPWA:本來想拆,但 _showPwaGuide 被 inline onclick 直接呼叫,',
    '  拆了會需要包 lazy wrapper,玩家點按鈕後有 ~1 秒延遲,體驗下降。權衡後保留',
    '【實作位置】',
    '・index.html stub:line ~36066(_ensureAdminPanelLoaded 模組載入器 + stub _showAdminStatsPanel)',
    '・admin_panel.js:獨立檔案,4,417 行 / 243 KB',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.45',
  ] },

  { ver:'v3.5.38', brief:[
    '🛡 修了三個雲端寫入相關的大問題!',
    '💰 之前升級至寶或召喚扣錢時,系統會誤判成「資料壞掉」而拒絕儲存,還會彈紅框嚇人',
    '📨 學生 6 分鐘內被連續通報 32 次的爆量問題也已止血',
    '🔧 老師的「強制重套」按鈕現在會自動讀備援槽,真正能救回 Lv1 帳號!',
  ], items:[
    '【問題 1:正常扣錢被當成「資料倒退」擋下】',
    '・v3.5.37 的健康度守門寫太緊:只要知識幣倒退 5,000 就拒絕儲存',
    '・但升級玉山巔峰之盾 Lv1→Lv2 要扣 15,000、買召喚水晶要扣 8~10,000',
    '・學生實際進步了(英雄解鎖 +1、最高等級 +1、總等級 +4),只因為買東西扣錢就被擋',
    '・更慘的是被擋下後會彈紅框「雲端寫入保護啟動」,嚇到學生以為存檔壞了',
    '【問題 2:同學生 6 分鐘自動回報 32 筆 BUG】',
    '・健康度守門擋下時會自動發 BUG 回報給老師,但完全沒有冷卻時間',
    '・學生戰鬥中每 30 秒、每行動一次都會自動存檔,每次都被擋、每次都送 BUG',
    '・結果:6 分鐘 32 筆完全相同的 BUG 回報塞爆老師的後台 + Firestore 配額警告',
    '【問題 3:老師「強制重套」救不回 Lv31 的真實資料】',
    '・老師 22:21 的 console 鐵證:safe 槽躺著 unlocked=50, maxLv=31, coins=219,364, bagItems=719',
    '・但主文件被污染成 unlocked=61, maxLv=0, coins=0 的空殼',
    '・舊版「強制重套」按鈕只讀主文件,完全沒去碰 safe 槽 → 救完還是 Lv0',
    '【這次怎麼修?】',
    '・✨ 守門邏輯重寫:英雄相關(unlocked / maxLv / totalLv)若全部進步或持平,knowledgeCoins',
    '  倒退一律視為正常扣款(至寶升級、買召喚水晶、商店購物等)→ 一律放行',
    '・✨ 守門硬擋值改成「極端值」才當災難(coins -100,000 / totalLv -100 / maxLv -5 / unlocked -5)',
    '・✨ 「英雄相關兩個指標一起倒退」才當作疑似帳號覆蓋 → 拒絕',
    '・✨ BUG 自動回報加 5 分鐘 cooldown(同帳號 5 分鐘內只送 1 筆),UI 紅框 30 秒內不重複彈',
    '・✨ 強制重套先呼叫 _fbDiagnoseAllSlots 掃三槽,選最豐富的當資料來源',
    '・✨ 如果來源是 safe / live 槽,順手把資料寫回主文件 + live 槽,下次登入直接讀到救援後的版本',
    '・✨ 順便修了小怪戰開場題沒出現時的卡死救援 — 救援判定改用 callback / phase 訊號,不再單靠',
    '  _advMiniBattleActive flag(這個 flag 可能在 race condition 中是錯的)',
    '【影響範圍】',
    '・三條救援路徑(管理員 3.7 工具、F12 強制重套、學生自救彈窗)現在都會走完整的 safe → main',
    '  寫回流程,殊途同歸',
    '・健康度守門誤殺率從「正常玩遊戲就會被擋」降到「只有真的覆蓋才擋」',
    '・BUG 自動回報從「6 分鐘 32 筆」降到「最多 5 分鐘 1 筆」',
    '【實作位置】',
    '・健康度守門邏輯:index.html line ~960-1030',
    '・BUG 回報 cooldown:index.html line ~1036-1083',
    '・強制重套三槽掃描:index.html line ~77611-77770',
    '・小怪戰救援判定:index.html line ~54005-54050',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.38',
  ] },

  { ver:'v3.5.37', brief:[
    '🆘 重大救援:解決學生帳號變回 Lv1 救不回來的根因!',
    '🔧 找到雲端 safe 備份槽「躺著真資料卻永遠沒被讀」的時序競態 BUG',
    '🛡 新增三槽診斷工具,管理員後台一鍵就能救援任何學生(或老師自己)',
  ], items:[
    '【問題】老師管理員帳號 clarebox123@gmail.com 變回 Lv1 怎麼也救不回',
    '・console 鐵證:safe 槽躺著 unlocked=50, maxLv=31, coins=219,364, bagItems=719 的完整資料',
    '・但 log 中完全沒有「[雙槽載入] 三槽分數: ...」訊息',
    '・只有「[_fbLoad] 從伺服器強制取得最新資料」 ← 走了 fallback 只讀主文件',
    '【根因鏈條】',
    '・_fbLoadSlot API 定義在 <script type="module">(async 載入)',
    '・gameCloudLoad 在普通 <script>(同步執行)',
    '・登入時序快 → window._fbLoadSlot 還是 undefined',
    '・gameCloudLoad 看到 _fbLoadSlot 不存在 → 走 fallback 只讀主文件',
    '・safe 槽的真資料一直安全地躺著,但永遠沒被讀取',
    '【這次怎麼修?五層修補】',
    '・✨ 1️⃣ 根因:gameCloudLoad 改成「先輪詢等 _fbLoadSlot 就緒(100ms × 5 秒)再走雙槽路徑」',
    '・✨ 2️⃣ 事前:_fbSaveLive 加健康度守門,用 transaction 比對雲端,差太多就拒絕寫入',
    '・✨ 3️⃣ 污染:_applySafeData 的 unlockedHeroes 合併改成「同 uid 才合併」,共用平板不會誤污染',
    '・✨ 4️⃣ 救援:新增 4 個救援 API(diagnose / restoreFromSlot / autoRestore / forceSafe)',
    '・✨ 5️⃣ UI:管理員後台新增「3.7 Lv1 救援工具」,uid 留空救自己、輸入 uid 救學生',
    '【操作步驟(老師救自己)】',
    '・部署 v3.5.37 → 用管理員帳號登入',
    '・Shift+F10 開管理員後台 → 滾到「🆘 3.7 Lv1 救援工具」',
    '・uid 留空(預設救自己)→ 點「✨ 一鍵自動還原最豐富版本」綠色按鈕',
    '・二次確認對話框會顯示要還原的內容(預期會選 safe 槽)→ 按確定',
    '・看到「✅ 已成功從 safe 槽還原」→ 重新整理頁面 → Lv31 / 21 萬知識幣回來',
    '【實作位置】',
    '・三槽掃描 API:index.html line ~2485-2645',
    '・管理員 3.7 工具 UI:index.html line ~36316',
    '・管理員 3.7 工具 JS:index.html line ~38759',
    '・gameCloudLoad 時序守門:index.html line ~59550',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.37',
  ] },

  { ver:'v3.5.36', brief:[
    '📱 PWA(裝到桌面那種)學生資料保護三件套!',
    '👀 學生第一次從桌面打開遊戲時會看到醒目的登入引導彈窗',
    '⚔ 戰鬥中如果跳出升版提示,會自動延後到戰鬥結束 5 秒後再套用,不會打斷',
    '⏰ 60 秒還沒登入會跳底部小提示條,免得學生以為「我的進度都不見了」',
  ], items:[
    '【背景】',
    '・iPad 上的 Safari 跟 PWA 安裝版是兩個獨立 webview,localStorage 完全隔離',
    '・學生先在 Safari 玩,再從桌面 PWA 開啟,PWA 端就是空白存檔',
    '・如果沒提示登入,學生會誤以為「我的進度都不見了」、亂點按鈕造成更大災難',
    '【三個保護功能】',
    '・✨ ① 首次 PWA 開啟登入引導 — standalone + 本機空白 + 未登入 → 醒目藍色脈動彈窗 +',
    '  「我去登入」按鈕自動聚焦 Google 登入區',
    '・✨ ② 戰鬥中升版橫幅守護 — MutationObserver 監聽 #_pwa-update-banner,戰鬥中(在小怪戰或',
    '  世界 BOSS 戰)會把原本綠色「立即套用」橫幅改成黃色「戰鬥結束後再套用」橫幅,',
    '  輪詢戰鬥結束 5 秒後自動恢復',
    '・✨ ③ 60 秒未登入提示 — standalone + 60 秒後仍未登入 + 沒有 ① 彈窗開著 → 底部從下方滑入',
    '  的小型藍色提示條',
    '【影響範圍】',
    '・所有用 PWA 玩遊戲的學生都受保護,不會再因為進入空白存檔的 PWA 而誤刪雲端資料',
    '・戰鬥中升版也不會打斷玩家(避免戰鬥中切到新版,世界 BOSS 連線層直接斷掉)',
    '【實作位置】',
    '・PWA 保護模組:index.html 檔尾獨立 IIFE 約 320 行',
    '・診斷工具:window._pwaProtectionDiag.{showFirstOpenGuide, showLoginNudge, isStandalone,',
    '  isLocalDataEmpty, isInBattle}',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.36',
  ] },

  { ver:'v3.5.35', brief:[
    '🏅 徹底修補 PWA 重複領獎章 BUG!',
    '🔍 找到 4 個獨立的自動補檢查觸發點,v3.5.34 只修了 1 個',
    '✨ 不只「日漸成熟」獎章,所有等級類、解鎖類、連擊類、答題類獎章都不會再重複領',
  ], items:[
    '【背景】',
    '・v3.5.34 修了 PWA 重複領「日漸成熟」獎章的單點問題,但部署後學生反映其他獎章還是重複領',
    '・深入排查發現系統有 4 個獨立的自動補檢查觸發點,v3.5.34 只修了 1 個',
    '【4 個觸發點】',
    '・① gameCloudLoad 內 _heroLevels merge 後立即補檢查 ← v3.5.34 已修',
    '・② _loadMedals 內 setTimeout 100ms 補檢查 ← v3.5.34 沒修',
    '・③ 登入後 setTimeout 1500ms 跑 _checkMedalsOnLogin ← v3.5.34 沒修',
    '・④ 訪客模式 1000ms 跑 _checkMedalsOnLogin(訪客無雲端,不需修)',
    '【這次怎麼修?】',
    '・✨ 統一改用 window._cloudLoadDone === true 輪詢守門(每 200~250ms 一次、最多 20 秒)',
    '・✨ 所有自動補檢查都要等雲端載入完成才執行',
    '・✨ 加 _medalBackfillScheduled debounce 旗標避免多次觸發',
    '・✨ _unlockMedal 加 localStorage 雙重檢查當第二層保險',
    '【受影響獎章】',
    '・等級類:hero_lv10/30/50、three_max',
    '・解鎖類:first_hero_unlock、unlock_5/10/20/30、all_heroes',
    '・技能類:first_skill_up、skill_max',
    '・知識幣類:coins_10000、coins_50000',
    '・答題類:first_correct、answers_20~2000、hard_100',
    '・擊敗類:defeat_chest/devil、chest_hunter_5、devil_slayer_5',
    '【三層保險防護網】',
    '・1️⃣ 時序守門(本版主修補)— 所有自動補檢查等 _cloudLoadDone === true',
    '・2️⃣ _unlockMedal localStorage 雙重檢查(v3.5.34 實作)',
    '・3️⃣ 超時 fallback(20 秒沒等到雲端就強制執行,有第 2 層擋)',
    '【實作位置】',
    '・gameCloudLoad 內補檢查(line ~58227)',
    '・_loadMedals 內 setTimeout(line ~75883)',
    '・登入後 _checkMedalsOnLogin(line ~3201)',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.35',
  ] },

  { ver:'v3.5.34', brief:[
    '🏅 修了 PWA 安裝版每次登入都彈「日漸成熟」獎章的 BUG!',
    '🔍 找到時序競態問題:雲端 _heroLevels 載入比 _medals 早,造成獎章重複領',
    '💡 改用「待補檢查」標記,延後到 _medals 雲端 merge 完成才檢查',
  ], items:[
    '【現象】',
    '・老師 PWA 安裝版每次登入都彈出「獎章解鎖:日漸成熟」+ 水晶 ×1 + 知識幣 +2,000',
    '・但 _medals 字典裡確實已經有這個獎章(playerMedals.hero_lv10.rewarded = true)',
    '・所以重複領了 N 次,雲端被加了 N × 2,000 知識幣',
    '【根因】',
    '・gameCloudLoad 內 _heroLevels merge 完成後立即呼叫 _checkMedalHeroLevel',
    '・但這時 _medals 還沒從雲端 merge 完成 → _unlockMedal 內 if(_medals[id]) return 判斷失效',
    '・結果是「明明已領過,但本地變數還沒同步,系統當成第一次解鎖」→ 再發一次',
    '【這次怎麼修?】',
    '・✨ 改用 window._pendingMedalLvCheck 標記,延後到 _medals 雲端 merge 完成才執行',
    '・✨ _unlockMedal 加 localStorage 雙重檢查(讀 lxps_*_progress 確認獎章列表是否已包含)',
    '・✨ 同時印 log「[獎章補檢查 v3.5.34] _medals 雲端 merge 完成,執行延後的英雄等級補檢查」',
    '【實作位置】',
    '・gameCloudLoad 內 _heroLevels merge 後標記(line ~58227)',
    '・_medals merge 後執行延後檢查(line ~58269)',
    '・_unlockMedal localStorage 雙重檢查(line ~76840)',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.34',
  ] },

  { ver:'v3.5.32', brief:[
    '🦸 新英雄登場!第 60 隻英雄「火柴人」!',
    '🎨 5 年 3 班張同學設計,LXPSGAME 第一位學生設計師!',
    '🔥 天賦「以火還火」反擊型,被攻擊時自動反擊火屬性傷害!',
  ], items:[
    '【新英雄能力】',
    '・🔥 火柴人(火屬性):HP 51 / 攻擊 7 / 特技 21 / 速度 21 = 100',
    '【天賦】',
    '・以火還火:被攻擊時自動反擊火屬性傷害(火屬性攻擊時反擊加倍)',
    '【技能】',
    '・S1「燃燒的火柴盒」:必中無視有利狀態的火焰連擊',
    '・S2「保持正能量」:全隊大治療 + 30% 迴避雙效',
    '・爆發「燃燒自己,照亮別人」:化身太陽火球玉石俱焚,造成大量火屬性傷害並燃燒全場',
    '【背景故事】',
    '・原本只是學生隨手在考卷上的塗鴉,陰錯陽差受到祝福而獲得生命',
    '・擁有了一顆永遠燃燒的赤誠之心,以火還火、不畏強敵',
    '【設計者】',
    '・5 年 3 班張同學設計(drummerelvis@gmail.com)',
    '・LXPSGAME 第一位學生設計師,值得紀念!',
    '【實作位置】',
    '・18 處插入位置:_PLAYER_HERO_NAMES、AVATARS、HERO_IMGS、HERO_PORTRAIT_LIBRARY、',
    '  HERO_BG_POS、HERO_BATTLE_CARD_POS、HERO_BIO designer、BURST_DB、HERO_LORE、HERO_TRAIT、',
    '  召喚池 ×2、ADMIN_ALL_HEROES、SUMMON_RARE_HEROES、HERO_CATEGORIES、HERO_HEX_OVERRIDE、',
    '  _TRAIT_LV_INFO、_STUDENT_DESIGNERS',
    '・圖片資源 火柴人.png 需上傳到 GitHub repo clarebox123jp-art/LXPSGAME/main/',
    '・CURRENT_VERSION 與 window._GAME_LOADED_VERSION 同步升級為 v3.5.32',
  ] },
