// ════════════════════════════════════════════════════════════════════
// student_roster.js — LXPSGAME 學生名冊(v3.5.59 新增)
//
//   用途:把學生班級/座號/姓名等個資資料,跟主程式碼分開保管
//
//   key:玩家 email(全小寫)
//   value:{ class, seatNo, surname, fullName }
//     class    — '5年3班'(必填,用於萃取年級數+班級數)
//     seatNo   — 1~35 整數(必填,個位數會自動補 0 為 2 碼)
//     surname  — '蔣'(必填,用於管理員後台/圖鑑/排行榜「同學」顯示)
//     fullName — '蔣小明'(★ v3.5.59 新增,僅用於好友面板顯示完整真名)
//
//   填寫範例:
//     'lsps110046@stu.lsps.tp.edu.tw': {
//       class:    '5年3班',
//       seatNo:   24,
//       surname:  '蔣',
//       fullName: '蔣小明',    // 老師可選填,沒填好友面板會 fallback 只顯示姓
//     },
//
//   顯示對照(同一筆名冊):
//     管理員後台 / 圖鑑 / 排行榜  → '5324蔣同學'          (姓 + 同學泛稱)
//     世界 BOSS 邀請好友彈窗      → '5324蔣同學' + 線上燈號
//     好友面板(玩家自己看)      → '5324蔣小明' + 線上燈號(若有 fullName)
//                              或 '5324蔣同學' + 線上燈號(若沒 fullName)
//
//   部署:
//     1. 把這個檔案放在 GitHub repo 跟 index.html 同層
//     2. 改 index.html 內的 <script src="student_roster.js?v=YYYYMMDD"> 破快取
//     3. 若不想上 GitHub(個資考量),加入 .gitignore 後手動上傳到伺服器
//
//   失敗安全:
//     若本檔載入失敗(404 / 網路問題),index.html 內 fallback 為空物件,
//     所有顯示走「無名冊資料 → 原 displayName」路徑,遊戲完全正常運作,
//     只是管理員後台短碼功能停擺。
//
// ════════════════════════════════════════════════════════════════════

window._STUDENT_ROSTER = {

  // ─── 3年1班 ─────────────────────────────────────────────────
  'lsps112055@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:1, surname:'黃', fullName:'黃聖軒' },
  'lsps112164@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:2, surname:'林', fullName:'林宸褕' },
  'lsps112187@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:3, surname:'莫', fullName:'莫健豪' },
  'lsps112030@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:4, surname:'林', fullName:'林則皓' },
  'lsps112165@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:5, surname:'謝', fullName:'謝茗臣' },
  'lsps110157@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:5, surname:'洪', fullName:'洪其緯' },
  'lsps112138@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:6, surname:'賴', fullName:'賴傳修' },
  'lsps112168@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:7, surname:'陳', fullName:'陳宇安' },
  'lsps112192@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:8, surname:'卓', fullName:'卓宇桐' },
  'lsps112188@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:9, surname:'張', fullName:'張博宸' },
  'lsps112011@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:10, surname:'黎', fullName:'黎承翰' },
  'lsps111213@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:11, surname:'鐘', fullName:'鐘弘燁' },
  'lsps112117@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:11, surname:'高', fullName:'高銘璟' },
  'lsps112066@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:12, surname:'江', fullName:'江柏緯' },
  'lsps112092@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:13, surname:'樊', fullName:'樊大可' },
  'lsps112043@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:21, surname:'劉', fullName:'劉名蕎' },
  'lsps112046@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:22, surname:'侯', fullName:'侯佳秀' },
  'lsps112150@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:23, surname:'林', fullName:'林右澄' },
  'lsps112072@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:24, surname:'梁', fullName:'梁佑曦' },
  'lsps112097@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:25, surname:'黃', fullName:'黃采漩' },
  'lsps112019@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:26, surname:'蔡', fullName:'蔡媛安' },
  'lsps111212@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:26, surname:'廖', fullName:'廖云曼' },
  'lsps112020@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:27, surname:'陳', fullName:'陳亮羽' },
  'lsps112075@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:28, surname:'張', fullName:'張語岑' },
  'lsps112180@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:29, surname:'張', fullName:'張語昕' },
  'lsps111051@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:30, surname:'高', fullName:'高楷茵' },
  'lsps112126@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:30, surname:'李', fullName:'李家妤' },
  'lsps112052@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:31, surname:'陳', fullName:'陳雨樂' },
  'lsps112132@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:32, surname:'許', fullName:'許恩琳' },
  'lsps112160@stu.lsps.tp.edu.tw': { class:'3年1班', seatNo:33, surname:'仝', fullName:'仝昭予' },

  // ─── 3年2班 ─────────────────────────────────────────────────
  'lsps112161@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:1, surname:'陳', fullName:'陳健瑋' },
  'lsps112082@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:2, surname:'楊', fullName:'楊瀚升' },
  'lsps112136@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:3, surname:'陳', fullName:'陳建維' },
  'lsps112083@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:4, surname:'湛', fullName:'湛睿恩Botu' },
  'lsps109006@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:4, surname:'吳', fullName:'吳明安' },
  'lsps112031@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:5, surname:'張', fullName:'張亮捷' },
  'lsps112084@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:6, surname:'郭', fullName:'郭承晰' },
  'lsps112007@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:7, surname:'劉', fullName:'劉杰禮' },
  'lsps112112@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:8, surname:'林', fullName:'林君嶴' },
  'lsps112009@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:9, surname:'蔡', fullName:'蔡昀宸' },
  'lsps112142@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:10, surname:'廖', fullName:'廖御棠' },
  'lsps112038@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:11, surname:'王', fullName:'王品翔' },
  'lsps112119@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:12, surname:'官', fullName:'官軒禾' },
  'lsps109039@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:12, surname:'方', fullName:'方詠程' },
  'lsps112120@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:21, surname:'陳', fullName:'陳曼妘' },
  'lsps112147@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:22, surname:'張', fullName:'張若羚' },
  'lsps112068@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:23, surname:'李', fullName:'李雨宸' },
  'lsps112069@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:24, surname:'簡', fullName:'簡子芯' },
  'lsps109100@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:24, surname:'曹', fullName:'曹媁茵' },
  'lsps112048@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:25, surname:'蔡', fullName:'蔡渝萱' },
  'lsps112177@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:26, surname:'柯', fullName:'柯宥岑' },
  'lsps110120@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:26, surname:'陳', fullName:'陳婕瑀' },
  'lsps112023@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:27, surname:'張', fullName:'張心樂' },
  'lsps112100@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:28, surname:'張', fullName:'張令宜' },
  'lsps112051@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:29, surname:'陳', fullName:'陳雨柔' },
  'lsps112131@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:30, surname:'高', fullName:'高語萱' },
  'lsps112183@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:31, surname:'莊', fullName:'莊沁穎' },
  'lsps112025@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:32, surname:'言', fullName:'言欣霏' },
  'lsps112106@stu.lsps.tp.edu.tw': { class:'3年2班', seatNo:33, surname:'高', fullName:'高芝縈' },

  // ─── 3年3班 ─────────────────────────────────────────────────
  'lsps112162@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:1, surname:'葉', fullName:'葉宸愷' },
  'lsps112028@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:2, surname:'嚴', fullName:'嚴楷博' },
  'lsps112058@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:3, surname:'阮', fullName:'阮智偉' },
  'lsps112029@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:4, surname:'黃', fullName:'黃子輔' },
  'lsps110078@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:4, surname:'劉', fullName:'劉立辰' },
  'lsps112003@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:5, surname:'簡', fullName:'簡毓恩' },
  'lsps112191@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:6, surname:'卓', fullName:'卓宸均' },
  'lsps112139@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:7, surname:'劉', fullName:'劉旭恩' },
  'lsps112062@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:8, surname:'洪', fullName:'洪梓宴' },
  'lsps112194@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:9, surname:'洪', fullName:'洪翊綸' },
  'lsps112115@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:10, surname:'高', fullName:'高晨凱' },
  'lsps112118@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:11, surname:'謝', fullName:'謝忻澄' },
  'lsps112012@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:12, surname:'陳', fullName:'陳睿凱' },
  'lsps112013@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:21, surname:'王', fullName:'王妤芯' },
  'lsps112070@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:22, surname:'張', fullName:'張薰予' },
  'lsps111069@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:22, surname:'任', fullName:'任語和' },
  'lsps112050@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:23, surname:'胡', fullName:'胡沛潔' },
  'lsps112179@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:24, surname:'陳', fullName:'陳妍瑄' },
  'lsps111145@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:25, surname:'李', fullName:'李宥彤' },
  'lsps112154@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:25, surname:'王', fullName:'王子霓' },
  'lsps112076@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:26, surname:'朱', fullName:'朱宣穎' },
  'lsps112155@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:27, surname:'王', fullName:'王皓芝' },
  'lsps112127@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:28, surname:'趙', fullName:'趙綺樂' },
  'lsps112130@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:29, surname:'施', fullName:'施采晴' },
  'lsps112103@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:30, surname:'張', fullName:'張文嫙' },
  'lsps112053@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:31, surname:'林', fullName:'林欣霈' },
  'lsps112026@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:32, surname:'陳', fullName:'陳禾蓉' },
  'lsps112105@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:33, surname:'高', fullName:'高卉婕' },
  'lsps112080@stu.lsps.tp.edu.tw': { class:'3年3班', seatNo:34, surname:'陳', fullName:'陳怡佳' },

  // ─── 3年4班 ─────────────────────────────────────────────────
  'lsps112081@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:1, surname:'謝', fullName:'謝語修' },
  'lsps112001@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:2, surname:'高', fullName:'高靖桓' },
  'lsps112060@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:3, surname:'莊', fullName:'莊詠樂' },
  'lsps112034@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:4, surname:'吳', fullName:'吳樂予' },
  'lsps112109@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:5, surname:'洪', fullName:'洪紀翔' },
  'lsps112110@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:6, surname:'張', fullName:'張書豫' },
  'lsps112064@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:7, surname:'蔡', fullName:'蔡孟軒' },
  'lsps112010@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:8, surname:'劉', fullName:'劉秉翰' },
  'lsps112170@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:9, surname:'張', fullName:'張崴凱' },
  'lsps111136@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:9, surname:'廖', fullName:'廖侑祖' },
  'lsps112039@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:10, surname:'郭', fullName:'郭廣志' },
  'lsps112146@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:11, surname:'鄭', fullName:'鄭至皓' },
  'lsps112067@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:12, surname:'高', fullName:'高嘉嶽' },
  'lsps112196@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:13, surname:'李', fullName:'李品謙' },
  'lsps110193@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:13, surname:'莊', fullName:'莊茗皓' },
  'lsps110195@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:15, surname:'林', fullName:'林駿辰' },
  'lsps110190@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:16, surname:'羅', fullName:'羅浩燁' },
  'lsps112174@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:21, surname:'杜', fullName:'杜俐穎' },
  'lsps112014@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:22, surname:'王', fullName:'王姸絜' },
  'lsps112094@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:23, surname:'高', fullName:'高可桐' },
  'lsps110093@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:24, surname:'方', fullName:'方禹心' },
  'lsps112122@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:24, surname:'何', fullName:'何佩玉' },
  'lsps110196@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:24, surname:'呂', fullName:'呂語婕' },
  'lsps110186@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:25, surname:'諶', fullName:'諶品樺' },
  'lsps112045@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:25, surname:'何', fullName:'何梓瑜' },
  'lsps112149@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:26, surname:'陳', fullName:'陳昕妤' },
  'lsps112049@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:27, surname:'黃', fullName:'黃亞菲' },
  'lsps112176@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:28, surname:'楊', fullName:'楊芸悠' },
  'lsps112022@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:29, surname:'曾', fullName:'曾華安' },
  'lsps112074@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:30, surname:'郭', fullName:'郭宇晴' },
  'lsps112102@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:31, surname:'王', fullName:'王紫綺' },
  'lsps112157@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:32, surname:'莊', fullName:'莊孟芯' },
  'lsps112185@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:33, surname:'蔡', fullName:'蔡采宸' },
  'lsps112133@stu.lsps.tp.edu.tw': { class:'3年4班', seatNo:34, surname:'蘇', fullName:'蘇昱潔' },

  // ─── 3年5班 ─────────────────────────────────────────────────
  'lsps112056@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:1, surname:'許', fullName:'許晨恩' },
  'lsps112135@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:2, surname:'楊', fullName:'楊文傑' },
  'lsps112057@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:3, surname:'陳', fullName:'陳宥旭' },
  'lsps112137@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:4, surname:'蘇', fullName:'蘇洺誼' },
  'lsps110159@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:4, surname:'張', fullName:'張威廉' },
  'lsps112166@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:5, surname:'林', fullName:'林品諠' },
  'lsps112032@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:6, surname:'高', fullName:'高胤宸' },
  'lsps110009@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:6, surname:'陳', fullName:'陳羿辰' },
  'lsps112169@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:7, surname:'王', fullName:'王翊' },
  'lsps112006@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:8, surname:'李', fullName:'李昊宸' },
  'lsps112008@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:9, surname:'徐', fullName:'徐榮廷' },
  'lsps112090@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:10, surname:'黃', fullName:'黃正融' },
  'lsps112116@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:11, surname:'劉', fullName:'劉容均' },
  'lsps112145@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:12, surname:'林', fullName:'林晅宇' },
  'lsps112172@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:13, surname:'萬', fullName:'萬睿甫' },
  'lsps112041@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:21, surname:'廖', fullName:'廖妍諠' },
  'lsps112016@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:22, surname:'陳', fullName:'陳品希' },
  'lsps112123@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:23, surname:'蔡', fullName:'蔡佩縈' },
  'lsps112153@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:24, surname:'王', fullName:'王靖' },
  'lsps112124@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:25, surname:'俞', fullName:'俞喬麒' },
  'lsps112125@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:26, surname:'崔', fullName:'崔嘉瑀' },
  'lsps112024@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:27, surname:'蔡', fullName:'蔡佳岑' },
  'lsps112077@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:28, surname:'李', fullName:'李婕稦' },
  'lsps112156@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:29, surname:'高', fullName:'高晨畔' },
  'lsps112101@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:30, surname:'高', fullName:'高語希' },
  'lsps112182@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:31, surname:'賴', fullName:'賴亞妡' },
  'lsps112079@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:32, surname:'朱', fullName:'朱亭羽' },
  'lsps111077@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:32, surname:'邱', fullName:'邱聿柔' },
  'lsps112054@stu.lsps.tp.edu.tw': { class:'3年5班', seatNo:33, surname:'劉', fullName:'劉名蓁' },

  // ─── 3年6班 ─────────────────────────────────────────────────
  'lsps112134@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:1, surname:'吳', fullName:'吳睿閎' },
  'lsps112085@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:2, surname:'洪', fullName:'洪胤翔' },
  'lsps112004@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:3, surname:'黃', fullName:'黃竑徹' },
  'lsps112086@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:4, surname:'陳', fullName:'陳陽翔' },
  'lsps112087@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:5, surname:'余', fullName:'余昕展' },
  'lsps112033@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:6, surname:'高', fullName:'高裕翔' },
  'lsps112140@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:7, surname:'白', fullName:'白舜宇' },
  'lsps112088@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:8, surname:'賴', fullName:'賴品亦' },
  'lsps112037@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:9, surname:'黃', fullName:'黃子宸' },
  'lsps112114@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:10, surname:'翟', fullName:'翟邦淵' },
  'lsps110087@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:10, surname:'陳', fullName:'陳羿廷' },
  'lsps111139@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:10, surname:'張', fullName:'張峻維' },
  'lsps112193@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:11, surname:'劉', fullName:'劉宸暟' },
  'lsps112195@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:12, surname:'劉', fullName:'劉宸睿' },
  'lsps112173@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:21, surname:'籃', fullName:'籃可晴' },
  'lsps112121@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:22, surname:'蔡', fullName:'蔡昀臻' },
  'lsps110117@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:22, surname:'鄭', fullName:'鄭衣宸' },
  'lsps112042@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:23, surname:'曾', fullName:'曾沛藝' },
  'lsps112015@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:24, surname:'陳', fullName:'陳品霓' },
  'lsps112096@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:25, surname:'高', fullName:'高瑞妤' },
  'lsps112152@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:26, surname:'趙', fullName:'趙子媞' },
  'lsps112189@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:27, surname:'萬', fullName:'萬品岑' },
  'lsps112181@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:28, surname:'花', fullName:'花若嘉' },
  'lsps112129@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:29, surname:'王', fullName:'王毓歆' },
  'lsps112158@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:30, surname:'姚', fullName:'姚紜馨' },
  'lsps112104@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:31, surname:'顏', fullName:'顏妘安' },
  'lsps112184@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:32, surname:'林', fullName:'林宜霏' },
  'lsps112027@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:33, surname:'歐', fullName:'歐陽萱芮' },
  'lsps112186@stu.lsps.tp.edu.tw': { class:'3年6班', seatNo:34, surname:'陳', fullName:'陳怡萍' },

  // ─── 3年7班 ─────────────────────────────────────────────────
  'lsps112002@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:1, surname:'王', fullName:'王崧唯' },
  'lsps112059@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:2, surname:'陳', fullName:'陳佳塏' },
  'lsps112005@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:3, surname:'許', fullName:'許弘耀' },
  'lsps112167@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:4, surname:'洪', fullName:'洪揚志' },
  'lsps112190@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:5, surname:'周', fullName:'周仕堂' },
  'lsps112036@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:6, surname:'黃', fullName:'黃布朗' },
  'lsps112111@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:7, surname:'王', fullName:'王倫昱' },
  'lsps112141@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:8, surname:'邱', fullName:'邱繼楷' },
  'lsps112089@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:9, surname:'簡', fullName:'簡宇圻' },
  'lsps112113@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:10, surname:'王', fullName:'王晨宇' },
  'lsps112063@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:11, surname:'張', fullName:'張睿家' },
  'lsps112171@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:12, surname:'許', fullName:'許宇崴' },
  'lsps112095@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:21, surname:'呂', fullName:'呂星辰' },
  'lsps112175@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:22, surname:'高', fullName:'高薇茵' },
  'lsps112148@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:23, surname:'高', fullName:'高紫芯' },
  'lsps112017@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:24, surname:'簡', fullName:'簡苡亘' },
  'lsps112044@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:25, surname:'張', fullName:'張書嫚' },
  'lsps112151@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:26, surname:'鄒', fullName:'鄒明叡' },
  'lsps112047@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:27, surname:'陳', fullName:'陳莉雲' },
  'lsps112073@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:28, surname:'吳', fullName:'吳子青' },
  'lsps112021@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:29, surname:'林', fullName:'林柔伊' },
  'lsps112178@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:30, surname:'古', fullName:'古繐甄' },
  'lsps112099@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:31, surname:'許', fullName:'許雅嵐' },
  'lsps112128@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:32, surname:'張', fullName:'張庭萓' },
  'lsps112078@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:33, surname:'机', fullName:'机愷甯' },
  'lsps112159@stu.lsps.tp.edu.tw': { class:'3年7班', seatNo:34, surname:'楊', fullName:'楊雲睎' },

  // ─── 3年8班 ─────────────────────────────────────────────────
  'lsps111012@stu.lsps.tp.edu.tw': { class:'3年8班', seatNo:11, surname:'鄭', fullName:'鄭楷叡' },

  // ─── 4年1班 ─────────────────────────────────────────────────
  'lsps111205@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:1, surname:'關', fullName:'關日森' },
  'lsps111107@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:2, surname:'余', fullName:'余安鈞' },
  'lsps109084@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:2, surname:'陳', fullName:'陳昊廷' },
  'lsps111183@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:3, surname:'謝', fullName:'謝忻叡' },
  'lsps111184@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:4, surname:'潘', fullName:'潘宣達' },
  'lsps111160@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:5, surname:'高', fullName:'高君祐' },
  'lsps111162@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:6, surname:'江', fullName:'江翊恩' },
  'lsps109063@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:7, surname:'梁', fullName:'梁祐維' },
  'lsps111009@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:7, surname:'高', fullName:'高振赫' },
  'lsps111163@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:8, surname:'黃', fullName:'黃晨祐' },
  'lsps111063@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:9, surname:'謝', fullName:'謝晉綸' },
  'lsps111065@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:10, surname:'梁', fullName:'梁博棟' },
  'lsps111222@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:11, surname:'張', fullName:'張博軒' },
  'lsps111044@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:21, surname:'余', fullName:'余明芝' },
  'lsps111144@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:22, surname:'江', fullName:'江梓萱' },
  'lsps111211@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:23, surname:'胡', fullName:'胡家好' },
  'lsps111021@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:24, surname:'江', fullName:'江若安' },
  'lsps111098@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:25, surname:'許', fullName:'許舒堯' },
  'lsps111200@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:27, surname:'何', fullName:'何沛珊' },
  'lsps111023@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:28, surname:'張', fullName:'張嘉紜' },
  'lsps111076@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:29, surname:'劉', fullName:'劉孜容' },
  'lsps111128@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:31, surname:'劉', fullName:'劉品樂' },
  'lsps111129@stu.lsps.tp.edu.tw': { class:'4年1班', seatNo:32, surname:'劉', fullName:'劉品寧' },

  // ─── 4年2班 ─────────────────────────────────────────────────
  'lsps111154@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:1, surname:'謝', fullName:'謝承勳' },
  'lsps111181@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:2, surname:'陳', fullName:'陳昱璋' },
  'lsps111130@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:3, surname:'魏', fullName:'魏傳熹' },
  'lsps111156@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:4, surname:'林', fullName:'林威信' },
  'lsps111054@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:5, surname:'張', fullName:'張宬碩' },
  'lsps111058@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:6, surname:'洪', fullName:'洪子安' },
  'lsps111006@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:7, surname:'汪', fullName:'汪靖凱' },
  'lsps111008@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:8, surname:'蔡', fullName:'蔡修傑' },
  'lsps111038@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:9, surname:'任', fullName:'任柏叡' },
  'lsps111039@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:10, surname:'李', fullName:'李海辰' },
  'lsps111114@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:11, surname:'林', fullName:'林柏澄' },
  'lsps111068@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:21, surname:'謝', fullName:'謝昀芯' },
  'lsps111095@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:22, surname:'陳', fullName:'陳可瑄' },
  'lsps111120@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:23, surname:'王', fullName:'王柔尹' },
  'lsps111045@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:24, surname:'李', fullName:'李品蓉' },
  'lsps111022@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:25, surname:'林', fullName:'林芓嬡' },
  'lsps111121@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:26, surname:'蘇', fullName:'蘇芊樺' },
  'lsps110150@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:27, surname:'高', fullName:'高楷媗' },
  'lsps111173@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:27, surname:'周', fullName:'周禹澄' },
  'lsps111073@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:28, surname:'林', fullName:'林宸頡' },
  'lsps111074@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:29, surname:'林', fullName:'林宸頤' },
  'lsps111201@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:30, surname:'楊', fullName:'楊又蓁' },
  'lsps111176@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:31, surname:'袁', fullName:'袁唯昕' },
  'lsps111204@stu.lsps.tp.edu.tw': { class:'4年2班', seatNo:32, surname:'吳', fullName:'吳宛儒' },

  // ─── 4年3班 ─────────────────────────────────────────────────
  'lsps111182@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:1, surname:'羅', fullName:'羅國銘' },
  'lsps111155@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:2, surname:'陳', fullName:'陳佑安' },
  'lsps111056@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:3, surname:'徐', fullName:'徐睿杰' },
  'lsps111057@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:4, surname:'高', fullName:'高偉權' },
  'lsps111158@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:6, surname:'林', fullName:'林家宥' },
  'lsps111159@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:7, surname:'陳', fullName:'陳品亦' },
  'lsps111186@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:8, surname:'廖', fullName:'廖子竣' },
  'lsps110059@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:9, surname:'王', fullName:'王允杰' },
  'lsps111086@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:9, surname:'林', fullName:'林靖凱' },
  'lsps111112@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:10, surname:'李', fullName:'李茂維' },
  'lsps111189@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:11, surname:'黃', fullName:'黃振赫' },
  'lsps111011@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:12, surname:'李', fullName:'李偲睿' },
  'lsps111067@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:21, surname:'施', fullName:'施芸婷' },
  'lsps111142@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:23, surname:'陳', fullName:'陳芓安' },
  'lsps111047@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:24, surname:'李', fullName:'李芙葇' },
  'lsps110173@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:24, surname:'陳', fullName:'陳芝睎' },
  'lsps111072@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:26, surname:'李', fullName:'李佳瑄' },
  'lsps111147@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:27, surname:'楊', fullName:'楊謹瑄' },
  'lsps111126@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:28, surname:'吳', fullName:'吳欣叡' },
  'lsps111101@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:29, surname:'劉', fullName:'劉美芯' },
  'lsps111026@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:30, surname:'林', fullName:'林沛瑜' },
  'lsps111103@stu.lsps.tp.edu.tw': { class:'4年3班', seatNo:31, surname:'林', fullName:'林湘芸' },

  // ─── 4年4班 ─────────────────────────────────────────────────
  'lsps111218@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:1, surname:'李', fullName:'李泓瑞' },
  'lsps111105@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:2, surname:'賴', fullName:'賴奕均' },
  'lsps111104@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:3, surname:'賴', fullName:'賴奕岑' },
  'lsps111001@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:4, surname:'蔡', fullName:'蔡忠穎' },
  'lsps111028@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:5, surname:'黃', fullName:'黃宥綸' },
  'lsps111053@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:6, surname:'游', fullName:'游承峰' },
  'lsps111084@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:7, surname:'周', fullName:'周睿哲' },
  'lsps111135@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:8, surname:'翁', fullName:'翁澤倫' },
  'lsps111090@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:10, surname:'張', fullName:'張得安' },
  'lsps110111@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:12, surname:'許', fullName:'許顥叡' },
  'lsps109068@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:14, surname:'謝', fullName:'謝尚融' },
  'lsps111041@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:22, surname:'洪', fullName:'洪歆玹' },
  'lsps111193@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:23, surname:'陳', fullName:'陳薏薰' },
  'lsps111195@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:24, surname:'陳', fullName:'陳品妍' },
  'lsps111143@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:25, surname:'郭', fullName:'郭禹汝' },
  'lsps111048@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:26, surname:'徐', fullName:'徐卉芯' },
  'lsps111097@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:27, surname:'周', fullName:'周品緁' },
  'lsps111171@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:28, surname:'陳', fullName:'陳玟圻' },
  'lsps111125@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:29, surname:'杜', fullName:'杜依璟' },
  'lsps111202@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:30, surname:'吳', fullName:'吳安綺' },
  'lsps111219@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:31, surname:'林', fullName:'林子瑄' },
  'lsps111150@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:32, surname:'李', fullName:'李亞霓' },
  'lsps111179@stu.lsps.tp.edu.tw': { class:'4年4班', seatNo:33, surname:'林', fullName:'林品溦' },

  // ─── 4年5班 ─────────────────────────────────────────────────
  'lsps111003@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:1, surname:'李', fullName:'李浚' },
  'lsps111032@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:2, surname:'周', fullName:'周品融' },
  'lsps111185@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:3, surname:'陳', fullName:'陳威廷' },
  'lsps111161@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:4, surname:'李', fullName:'李仁佐' },
  'lsps111061@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:6, surname:'黃', fullName:'黃俊赫' },
  'lsps111010@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:7, surname:'楊', fullName:'楊皓鈞' },
  'lsps111166@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:8, surname:'周', fullName:'周郁祥' },
  'lsps111064@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:9, surname:'張', fullName:'張瑞哲' },
  'lsps111115@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:10, surname:'謝', fullName:'謝浩允' },
  'lsps111140@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:11, surname:'白', fullName:'白昕右' },
  'lsps111014@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:21, surname:'陳', fullName:'陳妤菲' },
  'lsps111117@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:22, surname:'吳', fullName:'吳虹誼' },
  'lsps111192@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:23, surname:'林', fullName:'林芛安' },
  'lsps111119@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:24, surname:'陳', fullName:'陳昕' },
  'lsps111168@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:25, surname:'吳', fullName:'吳柏萱' },
  'lsps111046@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:26, surname:'陳', fullName:'陳語菲' },
  'lsps111071@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:27, surname:'張', fullName:'張凱芯' },
  'lsps111096@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:28, surname:'梁', fullName:'梁沐澴' },
  'lsps111174@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:29, surname:'謝', fullName:'謝欣妍' },
  'lsps111124@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:30, surname:'吳', fullName:'吳艾凝' },
  'lsps111127@stu.lsps.tp.edu.tw': { class:'4年5班', seatNo:33, surname:'張', fullName:'張靖敏' },

  // ─── 4年6班 ─────────────────────────────────────────────────
  'lsps111029@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:1, surname:'張', fullName:'張哲豪' },
  'lsps111081@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:2, surname:'鄧', fullName:'鄧宇傑' },
  'lsps111082@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:3, surname:'王', fullName:'王楷森' },
  'lsps111132@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:4, surname:'張', fullName:'張簡映澤' },
  'lsps111133@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:5, surname:'高', fullName:'高近凱' },
  'lsps111035@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:6, surname:'林', fullName:'林亞葆' },
  'lsps111157@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:7, surname:'邱', fullName:'邱子恩' },
  'lsps111005@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:8, surname:'陳', fullName:'陳楷燁' },
  'lsps110106@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:8, surname:'陳', fullName:'陳品翰' },
  'lsps111060@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:9, surname:'姫', fullName:'姫子桓' },
  'lsps111164@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:11, surname:'林', fullName:'林靖恩' },
  'lsps111220@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:12, surname:'黃', fullName:'黃柏呈' },
  'lsps111093@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:22, surname:'林', fullName:'林芸禾' },
  'lsps111019@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:23, surname:'江', fullName:'江欣霓' },
  'lsps109098@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:24, surname:'簡', fullName:'簡以媗' },
  'lsps111020@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:24, surname:'江', fullName:'江亞璇' },
  'lsps111221@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:25, surname:'莊', fullName:'莊惟絢' },
  'lsps111122@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:26, surname:'周', fullName:'周依璇' },
  'lsps111170@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:27, surname:'李', fullName:'李梓寧' },
  'lsps111146@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:28, surname:'黃', fullName:'黃芯宇' },
  'lsps111050@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:29, surname:'張', fullName:'張涵瑜' },
  'lsps111177@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:30, surname:'黃', fullName:'黃星嫚' },
  'lsps111149@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:31, surname:'劉', fullName:'劉培芸' },
  'lsps111151@stu.lsps.tp.edu.tw': { class:'4年6班', seatNo:33, surname:'陳', fullName:'陳語菲' },

  // ─── 4年7班 ─────────────────────────────────────────────────
  'lsps111083@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:1, surname:'戚', fullName:'戚健寧' },
  'lsps111134@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:2, surname:'王', fullName:'王建宇' },
  'lsps111085@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:3, surname:'陳', fullName:'陳思愷' },
  'lsps111004@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:4, surname:'洪', fullName:'洪晨軒' },
  'lsps111007@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:5, surname:'曾', fullName:'曾君禮' },
  'lsps111059@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:6, surname:'于', fullName:'于廷晞' },
  'lsps111087@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:7, surname:'李', fullName:'李仁佑' },
  'lsps111037@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:8, surname:'郭', fullName:'郭恩廷' },
  'lsps111138@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:9, surname:'胡', fullName:'胡聿伸' },
  'lsps111165@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:10, surname:'袁', fullName:'袁唯辰' },
  'lsps111116@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:11, surname:'陳', fullName:'陳渤修' },
  'lsps111191@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:12, surname:'王', fullName:'王佑頎' },
  'lsps111214@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:21, surname:'李', fullName:'李嘉軒' },
  'lsps111017@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:22, surname:'張', fullName:'張舒喬' },
  'lsps111094@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:23, surname:'陳', fullName:'陳語婕' },
  'lsps111042@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:24, surname:'翁', fullName:'翁葦臻' },
  'lsps111043@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:25, surname:'江', fullName:'江鈺' },
  'lsps111197@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:26, surname:'陳', fullName:'陳宥淇' },
  'lsps111099@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:27, surname:'王', fullName:'王至雅' },
  'lsps111172@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:28, surname:'羅', fullName:'羅苡芮' },
  'lsps111148@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:29, surname:'黃', fullName:'黃玟琁' },
  'lsps111203@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:30, surname:'高', fullName:'高羽欣' },
  'lsps111178@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:31, surname:'黃', fullName:'黃子欣' },
  'lsps111152@stu.lsps.tp.edu.tw': { class:'4年7班', seatNo:32, surname:'張', fullName:'張瑋秦' },

  // ─── 4年8班 ─────────────────────────────────────────────────
  'lsps111078@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:1, surname:'湯', fullName:'湯玉楷' },
  'lsps111002@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:2, surname:'林', fullName:'林立帷' },
  'lsps111131@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:3, surname:'陳', fullName:'陳禹任' },
  'lsps111108@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:4, surname:'涂', fullName:'涂藝新' },
  'lsps111031@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:5, surname:'蕢', fullName:'蕢亞倫' },
  'lsps111033@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:6, surname:'高', fullName:'高晨軒' },
  'lsps111206@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:7, surname:'章', fullName:'章承允' },
  'lsps111187@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:8, surname:'張', fullName:'張詣翔' },
  'lsps111137@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:9, surname:'詹', fullName:'詹立安' },
  'lsps111088@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:10, surname:'林', fullName:'林宸緯' },
  'lsps111091@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:21, surname:'白', fullName:'白欣幼' },
  'lsps111141@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:22, surname:'徐', fullName:'徐羽柔' },
  'lsps111018@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:23, surname:'王', fullName:'王芃之' },
  'lsps111169@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:24, surname:'邱', fullName:'邱子芸' },
  'lsps111123@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:25, surname:'陳', fullName:'陳右宣' },
  'lsps111198@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:26, surname:'張', fullName:'張昶昶' },
  'lsps111199@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:27, surname:'林', fullName:'林芸丞' },
  'lsps111100@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:28, surname:'黃', fullName:'黃之樂' },
  'lsps111175@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:29, surname:'謝', fullName:'謝采晏' },
  'lsps111052@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:30, surname:'張', fullName:'張雲雁' },
  'lsps111153@stu.lsps.tp.edu.tw': { class:'4年8班', seatNo:31, surname:'鄭', fullName:'鄭載萱' },

  // ─── 5年1班 ─────────────────────────────────────────────────
  'lsps110103@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:1, surname:'彭', fullName:'彭經宸' },
  'lsps110003@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:2, surname:'林', fullName:'林彥廷' },
  'lsps110079@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:3, surname:'郭', fullName:'郭宸睿' },
  'lsps110200@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:4, surname:'高', fullName:'高睿言' },
  'lsps110105@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:5, surname:'劉', fullName:'劉晨宇' },
  'lsps110133@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:6, surname:'蔡', fullName:'蔡智丞' },
  'lsps110163@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:7, surname:'胡', fullName:'胡聿呈' },
  'lsps110164@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:8, surname:'李', fullName:'李宥禾' },
  'lsps110088@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:9, surname:'林', fullName:'林承佑' },
  'lsps110135@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:10, surname:'劉', fullName:'劉葉浤鈺' },
  'lsps110035@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:11, surname:'林', fullName:'林昕佑' },
  'lsps110036@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:12, surname:'陳', fullName:'陳宥凱' },
  'lsps110139@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:13, surname:'高', fullName:'高茂凱' },
  'lsps110167@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:14, surname:'姜', fullName:'姜亦晟' },
  'lsps110116@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:15, surname:'林', fullName:'林劭諭' },
  'lsps110065@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:16, surname:'張', fullName:'張恩瑋' },
  'lsps110169@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:21, surname:'林', fullName:'林語希' },
  'lsps110068@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:22, surname:'周', fullName:'周禹希' },
  'lsps110171@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:23, surname:'許', fullName:'許儀馨' },
  'lsps110172@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:24, surname:'簡', fullName:'簡羽緁' },
  'lsps110147@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:25, surname:'王', fullName:'王梓妘' },
  'lsps110020@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:26, surname:'謝', fullName:'謝昀希' },
  'lsps110125@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:27, surname:'朱', fullName:'朱硏妡' },
  'lsps110183@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:28, surname:'李', fullName:'李昀容' },
  'lsps110126@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:29, surname:'張', fullName:'張芯寧' },
  'lsps110050@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:30, surname:'李', fullName:'李曙安' },
  'lsps110076@stu.lsps.tp.edu.tw': { class:'5年1班', seatNo:31, surname:'徐', fullName:'徐芷妍' },

  // ─── 5年2班 ─────────────────────────────────────────────────
  'lsps110191@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:1, surname:'李', fullName:'李堅強' },
  'lsps110051@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:2, surname:'鐘', fullName:'鐘豊為' },
  'lsps110153@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:3, surname:'萬', fullName:'萬睿楠' },
  'lsps110054@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:4, surname:'朱', fullName:'朱繹銨' },
  'lsps110028@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:5, surname:'張', fullName:'張博恩' },
  'lsps110057@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:6, surname:'謝', fullName:'謝承軒' },
  'lsps110081@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:7, surname:'許', fullName:'許宇慶' },
  'lsps109144@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:8, surname:'高', fullName:'高晟瑄' },
  'lsps110083@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:8, surname:'黃', fullName:'黃晟恩' },
  'lsps110132@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:9, surname:'朱', fullName:'朱宸毅' },
  'lsps110086@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:11, surname:'江', fullName:'江宸安' },
  'lsps110010@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:12, surname:'李', fullName:'李翊誠' },
  'lsps110134@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:13, surname:'羅', fullName:'羅晨豪' },
  'lsps110109@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:14, surname:'高', fullName:'高誠遠' },
  'lsps110011@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:15, surname:'張', fullName:'張安均' },
  'lsps110091@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:16, surname:'韓', fullName:'韓愷宸' },
  'lsps110199@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:17, surname:'卓', fullName:'卓秉均' },
  'lsps110189@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:21, surname:'梁', fullName:'梁迎希' },
  'lsps110016@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:22, surname:'廖', fullName:'廖婉芸' },
  'lsps110070@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:23, surname:'段', fullName:'段書凡' },
  'lsps110019@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:24, surname:'張', fullName:'張凱晴' },
  'lsps110073@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:25, surname:'林', fullName:'林夏天' },
  'lsps110182@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:26, surname:'陳', fullName:'陳禹馨' },
  'lsps110176@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:27, surname:'劉', fullName:'劉品萱' },
  'lsps110022@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:28, surname:'簡', fullName:'簡婕伃' },
  'lsps110100@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:29, surname:'張', fullName:'張紫晴' },
  'lsps110023@stu.lsps.tp.edu.tw': { class:'5年2班', seatNo:30, surname:'張', fullName:'張瑜庭' },

  // ─── 5年3班 ─────────────────────────────────────────────────
  'lsps110025@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:1, surname:'張', fullName:'張宸豪' },
  'lsps110052@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:2, surname:'宋', fullName:'宋承霖' },
  'lsps110180@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:3, surname:'陳', fullName:'陳博文' },
  'lsps110004@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:4, surname:'詹', fullName:'詹元佑' },
  'lsps110160@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:5, surname:'林', fullName:'林誼睿' },
  'lsps110082@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:6, surname:'柯', fullName:'柯靖為' },
  'lsps110007@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:8, surname:'周', fullName:'周道敬' },
  'lsps110107@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:9, surname:'李', fullName:'李冠任' },
  'lsps110089@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:10, surname:'張', fullName:'張凱勛' },
  'lsps110032@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:11, surname:'劉', fullName:'劉宸佑' },
  'lsps110090@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:12, surname:'鄧', fullName:'鄧家奕' },
  'lsps110062@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:13, surname:'巫', fullName:'巫昕祐' },
  'lsps110038@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:14, surname:'張', fullName:'張允謙' },
  'lsps110178@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:15, surname:'張', fullName:'張業司' },
  'lsps110039@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:16, surname:'蔡', fullName:'蔡曜丞' },
  'lsps110041@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:21, surname:'張', fullName:'張書語' },
  'lsps110094@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:22, surname:'古', fullName:'古曼君' },
  'lsps110149@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:23, surname:'龎', fullName:'龎苡睿' },
  'lsps110046@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:24, surname:'蔣', fullName:'蔣紫晴' },
  'lsps110174@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:25, surname:'陳', fullName:'陳宥臻' },
  'lsps110175@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:26, surname:'高', fullName:'高芝嬅' },
  'lsps110047@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:27, surname:'林', fullName:'林昕辰' },
  'lsps110049@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:28, surname:'陳', fullName:'陳玟伶' },
  'lsps110187@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:29, surname:'黃', fullName:'黃稚喜' },
  'lsps110188@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:30, surname:'黃', fullName:'黃稚善' },
  'lsps110177@stu.lsps.tp.edu.tw': { class:'5年3班', seatNo:31, surname:'柯', fullName:'柯禹安' },

  // ─── 5年4班 ─────────────────────────────────────────────────
  'lsps110026@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:1, surname:'歐', fullName:'歐宣聖' },
  'lsps110127@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:2, surname:'高', fullName:'高廷睿' },
  'lsps110077@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:3, surname:'周', fullName:'周世學' },
  'lsps110002@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:4, surname:'李', fullName:'李弦城' },
  'lsps110156@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:5, surname:'李', fullName:'李宜泓' },
  'lsps110027@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:6, surname:'林', fullName:'林廷之' },
  'lsps110128@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:7, surname:'陳', fullName:'陳威達' },
  'lsps110104@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:8, surname:'陳', fullName:'陳煥彬' },
  'lsps110005@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:9, surname:'潘', fullName:'潘昱辰' },
  'lsps110029@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:10, surname:'陳', fullName:'陳柏安' },
  'lsps110085@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:11, surname:'彭', fullName:'彭依鋒' },
  'lsps110061@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:12, surname:'黃', fullName:'黃秉弘' },
  'lsps110165@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:13, surname:'張', fullName:'張博堯' },
  'lsps110110@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:14, surname:'許', fullName:'許立閎' },
  'lsps110013@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:15, surname:'莊', fullName:'莊允樂' },
  'lsps110014@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:16, surname:'劉', fullName:'劉安喆' },
  'lsps110142@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:21, surname:'張', fullName:'張亞筠' },
  'lsps110143@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:22, surname:'李', fullName:'李芃蓁' },
  'lsps110118@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:23, surname:'黃', fullName:'黃婕羚' },
  'lsps110146@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:24, surname:'陳', fullName:'陳逸倢' },
  'lsps110170@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:25, surname:'丁', fullName:'丁冠伶' },
  'lsps110017@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:26, surname:'林', fullName:'林子馨' },
  'lsps110181@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:27, surname:'梁', fullName:'梁瑀恩' },
  'lsps110021@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:28, surname:'吳', fullName:'吳沛儀' },
  'lsps110048@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:29, surname:'楊', fullName:'楊寓如' },
  'lsps110098@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:30, surname:'沈', fullName:'沈芯婕' },
  'lsps110152@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:31, surname:'許', fullName:'許芷菱' },
  'lsps110101@stu.lsps.tp.edu.tw': { class:'5年4班', seatNo:32, surname:'裴', fullName:'裴珮芸' },

  // ─── 5年5班 ─────────────────────────────────────────────────
  'lsps110053@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:1, surname:'吳', fullName:'吳向穠' },
  'lsps110056@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:2, surname:'朱', fullName:'朱信霖' },
  'lsps110130@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:3, surname:'王', fullName:'王右葳' },
  'lsps110084@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:4, surname:'曾', fullName:'曾彥儒' },
  'lsps110006@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:5, surname:'陳', fullName:'陳睿智' },
  'lsps110162@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:6, surname:'顏', fullName:'顏楀宸' },
  'lsps110008@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:7, surname:'黃', fullName:'黃懋安' },
  'lsps109140@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:8, surname:'鄒', fullName:'鄒定衡' },
  'lsps110192@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:8, surname:'陳', fullName:'陳柏睿' },
  'lsps110031@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:9, surname:'許', fullName:'許皓閔' },
  'lsps110198@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:10, surname:'文', fullName:'文澤棟' },
  'lsps110033@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:11, surname:'翁', fullName:'翁嵦晏' },
  'lsps110137@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:12, surname:'閻', fullName:'閻漢昀' },
  'lsps110113@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:13, surname:'陳', fullName:'陳禹劭' },
  'lsps110114@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:14, surname:'李', fullName:'李卿宏' },
  'lsps110115@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:15, surname:'陳', fullName:'陳品均' },
  'lsps110064@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:16, surname:'陳', fullName:'陳廷羽' },
  'lsps110144@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:21, surname:'吳', fullName:'吳梓勤' },
  'lsps110066@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:22, surname:'湛', fullName:'湛芮熙‧亞娃伊' },
  'lsps110092@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:23, surname:'王', fullName:'王冠雅' },
  'lsps110043@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:24, surname:'高', fullName:'高晨芝' },
  'lsps110044@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:25, surname:'蔡', fullName:'蔡伃甯' },
  'lsps110122@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:26, surname:'張', fullName:'張可妤' },
  'lsps110071@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:27, surname:'楊', fullName:'楊善筑' },
  'lsps110151@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:28, surname:'熊', fullName:'熊梓芸' },
  'lsps110194@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:29, surname:'韓', fullName:'韓馨宇' },
  'lsps110097@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:30, surname:'田', fullName:'田歆雅' },
  'lsps110099@stu.lsps.tp.edu.tw': { class:'5年5班', seatNo:31, surname:'黃', fullName:'黃薰儀' },

  // ─── 5年6班 ─────────────────────────────────────────────────
  'lsps110197@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:1, surname:'鄧', fullName:'鄧兆洋' },
  'lsps110154@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:2, surname:'賴', fullName:'賴正寧' },
  'lsps110001@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:3, surname:'盧', fullName:'盧楷程' },
  'lsps110055@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:4, surname:'周', fullName:'周祺硯' },
  'lsps110184@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:5, surname:'鄭', fullName:'鄭宇陽' },
  'lsps110131@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:6, surname:'高', fullName:'高睿鴻' },
  'lsps110030@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:7, surname:'周', fullName:'周栢鋒' },
  'lsps110161@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:8, surname:'李', fullName:'李家全' },
  'lsps110058@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:9, surname:'張', fullName:'張喬鈞' },
  'lsps110060@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:10, surname:'龔', fullName:'龔哲均' },
  'lsps110108@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:11, surname:'黃', fullName:'黃偉晏' },
  'lsps110034@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:12, surname:'高', fullName:'高立恩' },
  'lsps110112@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:13, surname:'蕭', fullName:'蕭梓杰' },
  'lsps110138@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:14, surname:'林', fullName:'林禹澄' },
  'lsps110037@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:15, surname:'黃', fullName:'黃一賢' },
  'lsps110012@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:16, surname:'譚', fullName:'譚森遠' },
  'lsps110185@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:21, surname:'吳', fullName:'吳惠庭' },
  'lsps110145@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:22, surname:'蕭', fullName:'蕭絜芸' },
  'lsps110069@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:23, surname:'許', fullName:'許微欣' },
  'lsps110018@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:24, surname:'黃', fullName:'黃全妍' },
  'lsps110119@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:25, surname:'李', fullName:'李天妘' },
  'lsps110148@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:26, surname:'劉', fullName:'劉芸希' },
  'lsps110123@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:27, surname:'曾', fullName:'曾沛馨' },
  'lsps110124@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:28, surname:'胡', fullName:'胡妤秀' },
  'lsps110095@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:29, surname:'翁', fullName:'翁湘諭' },
  'lsps110072@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:30, surname:'何', fullName:'何牧蓁' },
  'lsps110074@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:31, surname:'余', fullName:'余威璇' },
  'lsps110096@stu.lsps.tp.edu.tw': { class:'5年6班', seatNo:32, surname:'林', fullName:'林汘樺' },

  // ─── 6年1班 ─────────────────────────────────────────────────
  'lsps109001@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:1, surname:'楊', fullName:'楊傑翔' },
  'lsps109055@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:2, surname:'黃', fullName:'黃嘉騰' },
  'lsps109083@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:3, surname:'蔣', fullName:'蔣晟煜' },
  'lsps109059@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:4, surname:'何', fullName:'何宇恩' },
  'lsps109137@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:5, surname:'林', fullName:'林承叡' },
  'lsps109061@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:6, surname:'劉', fullName:'劉宇恩' },
  'lsps109008@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:7, surname:'陳', fullName:'陳諾' },
  'lsps109109@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:8, surname:'林', fullName:'林祐霆' },
  'lsps109110@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:9, surname:'許', fullName:'許凱荃' },
  'lsps109111@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:10, surname:'鄧', fullName:'鄧年成' },
  'lsps109040@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:11, surname:'謝', fullName:'謝秉宸' },
  'lsps109067@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:12, surname:'孟', fullName:'孟德揚' },
  'lsps109181@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:13, surname:'林', fullName:'林心樂' },
  'lsps109042@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:21, surname:'蘇', fullName:'蘇羿璇' },
  'lsps109043@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:22, surname:'彭', fullName:'彭佩瑜' },
  'lsps109017@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:23, surname:'磨', fullName:'磨彥芯' },
  'lsps109069@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:24, surname:'張', fullName:'張宇惠' },
  'lsps109072@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:25, surname:'陳', fullName:'陳品妤' },
  'lsps109097@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:26, surname:'蔡', fullName:'蔡昀樺' },
  'lsps109177@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:27, surname:'麥', fullName:'麥芷瑜' },
  'lsps109125@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:28, surname:'陳', fullName:'陳昱穎' },
  'lsps109049@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:29, surname:'梁', fullName:'梁元禎' },
  'lsps109155@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:30, surname:'許', fullName:'許甯甯' },
  'lsps109156@stu.lsps.tp.edu.tw': { class:'6年1班', seatNo:31, surname:'文', fullName:'文潤美' },

  // ─── 6年2班 ─────────────────────────────────────────────────
  'lsps109002@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:1, surname:'吳', fullName:'吳宗樺' },
  'lsps109086@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:2, surname:'高', fullName:'高源邑' },
  'lsps109108@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:3, surname:'張', fullName:'張宇杰' },
  'lsps109009@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:4, surname:'李', fullName:'李宣甫' },
  'lsps109112@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:5, surname:'陳', fullName:'陳宗擇' },
  'lsps109089@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:6, surname:'何', fullName:'何昱寬' },
  'lsps109090@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:7, surname:'高', fullName:'高俊皓' },
  'lsps109180@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:8, surname:'林', fullName:'林宸緯' },
  'lsps109166@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:9, surname:'林', fullName:'林佑丞' },
  'lsps109038@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:10, surname:'陳', fullName:'陳奐宇' },
  'lsps109065@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:11, surname:'陳', fullName:'陳宣睿' },
  'lsps109116@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:12, surname:'林', fullName:'林彥廷' },
  'lsps109066@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:13, surname:'陳', fullName:'陳豪佑' },
  'lsps109170@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:14, surname:'薛', fullName:'薛敦亮' },
  'lsps109186@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:15, surname:'闕', fullName:'闕高明達' },
  'lsps109148@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:21, surname:'趙', fullName:'趙芯彤' },
  'lsps109019@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:22, surname:'高', fullName:'高榆晴' },
  'lsps109099@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:23, surname:'陳', fullName:'陳玟如' },
  'lsps109151@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:24, surname:'黃', fullName:'黃芊樺' },
  'lsps109152@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:25, surname:'魏', fullName:'魏詠玶' },
  'lsps109079@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:26, surname:'游', fullName:'游芝緁' },
  'lsps109130@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:27, surname:'莊', fullName:'莊昕紜' },
  'lsps109053@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:28, surname:'蒙', fullName:'蒙語樂' },
  'lsps109026@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:29, surname:'林', fullName:'林采嫻' },
  'lsps109027@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:30, surname:'陳', fullName:'陳雨青' },
  'lsps109158@stu.lsps.tp.edu.tw': { class:'6年2班', seatNo:31, surname:'陳', fullName:'陳亭瑄' },

  // ─── 6年3班 ─────────────────────────────────────────────────
  'lsps109169@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:1, surname:'胡', fullName:'胡嘉輝' },
  'lsps109028@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:2, surname:'闕', fullName:'闕睿佑' },
  'lsps109029@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:3, surname:'李', fullName:'李和謙' },
  'lsps109030@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:4, surname:'李', fullName:'李奕樺' },
  'lsps109004@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:5, surname:'顧', fullName:'顧修寧' },
  'lsps109031@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:6, surname:'高', fullName:'高晨恩' },
  'lsps109136@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:7, surname:'劉', fullName:'劉奇恩' },
  'lsps109007@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:8, surname:'李', fullName:'李祐丞' },
  'lsps109165@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:9, surname:'王', fullName:'王禹程' },
  'lsps109088@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:10, surname:'梁', fullName:'梁博閔' },
  'lsps109142@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:11, surname:'王', fullName:'王昱翔' },
  'lsps109119@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:12, surname:'黃', fullName:'黃獻睿' },
  'lsps109041@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:13, surname:'羅', fullName:'羅翊峰' },
  'lsps109058@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:14, surname:'洪', fullName:'洪浩誠' },
  'lsps109016@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:21, surname:'高', fullName:'高榆婷' },
  'lsps109018@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:22, surname:'黃', fullName:'黃子薰' },
  'lsps109095@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:23, surname:'高', fullName:'高若琳' },
  'lsps109070@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:24, surname:'鄭', fullName:'鄭如妏' },
  'lsps109122@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:25, surname:'賴', fullName:'賴姸安' },
  'lsps109126@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:26, surname:'潘', fullName:'潘宣彤' },
  'lsps109103@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:27, surname:'顏', fullName:'顏岑安' },
  'lsps109078@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:28, surname:'潘', fullName:'潘君彤' },
  'lsps109023@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:29, surname:'許', fullName:'許雅涵' },
  'lsps109131@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:30, surname:'陳', fullName:'陳以真' },
  'lsps109104@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:31, surname:'蘇', fullName:'蘇韻方' },
  'lsps109184@stu.lsps.tp.edu.tw': { class:'6年3班', seatNo:32, surname:'張', fullName:'張庭瑄' },

  // ─── 6年4班 ─────────────────────────────────────────────────
  'lsps109054@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:1, surname:'林', fullName:'林禹杭' },
  'lsps109056@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:2, surname:'蘇', fullName:'蘇胤愷' },
  'lsps109081@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:3, surname:'施', fullName:'施定宸' },
  'lsps109082@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:4, surname:'施', fullName:'施定謙' },
  'lsps109139@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:5, surname:'陸', fullName:'陸霆叡' },
  'lsps109035@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:6, surname:'黃', fullName:'黃靖墉' },
  'lsps109036@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:7, surname:'高', fullName:'高浚宸' },
  'lsps109114@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:8, surname:'宓', fullName:'宓承翰' },
  'lsps109143@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:9, surname:'陳', fullName:'陳柏鈞' },
  'lsps109064@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:10, surname:'何', fullName:'何秉樺' },
  'lsps109146@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:11, surname:'林', fullName:'林劼' },
  'lsps109093@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:12, surname:'魏', fullName:'魏辰翰' },
  'lsps109160@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:13, surname:'吳', fullName:'吳曜宇' },
  'lsps109015@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:14, surname:'李', fullName:'李後吶多' },
  'lsps109046@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:21, surname:'黎', fullName:'黎芷瑄' },
  'lsps109121@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:22, surname:'謝', fullName:'謝沛恩' },
  'lsps109074@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:23, surname:'張', fullName:'張若霖' },
  'lsps109075@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:24, surname:'陳', fullName:'陳茵芃' },
  'lsps109076@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:25, surname:'蕭', fullName:'蕭宥恩' },
  'lsps109050@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:26, surname:'蔡', fullName:'蔡旻妘' },
  'lsps109020@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:27, surname:'翟', fullName:'翟譽絜' },
  'lsps109102@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:28, surname:'高', fullName:'高語婕' },
  'lsps109171@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:29, surname:'阮', fullName:'阮安曼' },
  'lsps109052@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:30, surname:'徐', fullName:'徐羽貞' },
  'lsps109159@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:31, surname:'高', fullName:'高藝庭' },
  'lsps109183@stu.lsps.tp.edu.tw': { class:'6年4班', seatNo:32, surname:'曾', fullName:'曾譯萱' },

  // ─── 6年5班 ─────────────────────────────────────────────────
  'lsps109057@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:1, surname:'鄭', fullName:'鄭惟仁' },
  'lsps109135@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:2, surname:'李', fullName:'李冠丞' },
  'lsps109032@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:3, surname:'黃', fullName:'黃恩予' },
  'lsps109005@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:4, surname:'王', fullName:'王梓立' },
  'lsps109060@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:5, surname:'陳', fullName:'陳威愷' },
  'lsps109085@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:6, surname:'張', fullName:'張循光' },
  'lsps109138@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:7, surname:'吳', fullName:'吳致均' },
  'lsps109141@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:9, surname:'周', fullName:'周子翔' },
  'lsps109113@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:10, surname:'謝', fullName:'謝承叡' },
  'lsps109037@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:11, surname:'呂', fullName:'呂晟睿' },
  'lsps109115@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:12, surname:'簡', fullName:'簡茂森' },
  'lsps109145@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:13, surname:'邱', fullName:'邱煜翔' },
  'lsps109120@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:14, surname:'周', fullName:'周睿宸' },
  'lsps109182@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:15, surname:'陳', fullName:'陳宥辰' },
  'lsps109044@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:21, surname:'李', fullName:'李若榆' },
  'lsps109045@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:22, surname:'高', fullName:'高紫綺' },
  'lsps109073@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:23, surname:'蔡', fullName:'蔡欣彤' },
  'lsps109047@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:24, surname:'邱', fullName:'邱奕瑄' },
  'lsps109124@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:25, surname:'高', fullName:'高語晨' },
  'lsps109101@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:26, surname:'董', fullName:'董芝寧' },
  'lsps109022@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:27, surname:'王', fullName:'王乙臻' },
  'lsps109129@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:28, surname:'張', fullName:'張采絜' },
  'lsps109157@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:29, surname:'陳', fullName:'陳芝妤' },
  'lsps109025@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:30, surname:'錢', fullName:'錢文媛' },
  'lsps109178@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:31, surname:'周', fullName:'周昱岑' },
  'lsps109179@stu.lsps.tp.edu.tw': { class:'6年5班', seatNo:32, surname:'曹', fullName:'曹右霏' },

  // ─── 6年6班 ─────────────────────────────────────────────────
  'lsps109133@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:1, surname:'徐', fullName:'徐翊崴' },
  'lsps109003@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:2, surname:'汪', fullName:'汪弈均' },
  'lsps109033@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:3, surname:'劉', fullName:'劉至禮' },
  'lsps109062@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:4, surname:'王', fullName:'王晨哲' },
  'lsps109034@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:5, surname:'徐', fullName:'徐靖瑋' },
  'lsps109087@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:6, surname:'許', fullName:'許佳睎' },
  'lsps109172@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:7, surname:'簡', fullName:'簡碩辰' },
  'lsps109010@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:8, surname:'黃', fullName:'黃振庭' },
  'lsps109012@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:9, surname:'林', fullName:'林采陞' },
  'lsps109091@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:10, surname:'陳', fullName:'陳裕禮' },
  'lsps109117@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:11, surname:'郭', fullName:'郭廣謙' },
  'lsps109094@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:12, surname:'黃', fullName:'黃正閔' },
  'lsps109161@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:13, surname:'張', fullName:'張鉑敬' },
  'lsps109185@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:14, surname:'劉', fullName:'劉宸睿' },
  'lsps109096@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:21, surname:'陳', fullName:'陳柏妤' },
  'lsps109021@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:22, surname:'劉', fullName:'劉芯汝' },
  'lsps109051@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:23, surname:'林', fullName:'林胤妤' },
  'lsps109153@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:24, surname:'林', fullName:'林采潔' },
  'lsps109154@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:25, surname:'張', fullName:'張芸緁' },
  'lsps109127@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:26, surname:'楊', fullName:'楊琋潔' },
  'lsps109128@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:27, surname:'郭', fullName:'郭硯昕' },
  'lsps109024@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:28, surname:'蔡', fullName:'蔡昀樺' },
  'lsps109132@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:29, surname:'胡', fullName:'胡予歆' },
  'lsps109080@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:30, surname:'張', fullName:'張芷瑀' },
  'lsps109106@stu.lsps.tp.edu.tw': { class:'6年6班', seatNo:31, surname:'李', fullName:'李品萱' },

};

// 通知 index.html 名冊已載入完成(若有人在等)
try {
  if (typeof window !== 'undefined' && typeof window._onStudentRosterReady === 'function') {
    window._onStudentRosterReady();
  }
} catch(e) {}

console.info('[student_roster.js v3.5.59] 已載入,共 ' + Object.keys(window._STUDENT_ROSTER).length + ' 筆名冊資料');
