/* ══════════════════════════════════════════════════════════════════
   暫存區:原「回收小英雄」關卡(id:'recycle')移出的 80 題回收相關內容
   ══════════════════════════════════════════════════════════════════
   ★ v1.62.0(2026-09-09)老師需求「木柵回收小英雄整題改成磁鐵、電流相關單元」時,
   從該關卡移出的原始回收題目,老師裁定「先擱置,以後再拿出來用」——本檔案不被任何
   <script> 引用、不影響遊戲運作,純粹是保存原始資料以便未來需要時可以直接複製回
   minigame_db.js 使用(或安排到別的關卡)。

   內容組成(共 80 項,依原本在 items 陣列中的順序):
   ①前 50 項(engine:'quiz')— 回收科學小博士選擇題,涵蓋寶特瓶/鐵罐/鋁罐/鋁箔包/
     紙張/紙箱/衛生紙/洗髮精瓶/陶瓷碗/吸管等 10 種回收物的材質、環保知識與分類判斷。
   ②後 30 項(t:/b: 格式)— 拖曳分類題,把物品拖進「紙類/塑膠/金屬/一般垃圾」四個
     回收桶;其中 10 項帶 pic 欄位(有照片)、20 項純文字。
     ⚠ 這 30 項裡有 10 項(帶照片的那 10 項對應的物品)已在同一輪改成新的內容,
     搬進迷宮探險王(id:'maze')第一關的 3 組新 variants(紙類回收/塑膠類回收/可以
     回收);迷宮那邊是重新編寫的新題目(石板只需 6 格、答案敘述也不同),不是直接搬
     這裡的原始資料,所以這份原始 80 項全部完整保留,供老師之後仍要用時參考或直接
     複製使用。

   若要恢復:整段 items 陣列內容可以直接貼回 minigame_db.js 的 recycle 關卡
   items:[ ] 裡(建議貼在現有 50 題電磁鐵內容之前或之後皆可),或挑選其中幾項另外
   安排到別的關卡。
   ══════════════════════════════════════════════════════════════════ */
window.MG_STASH_RECYCLE_REMOVED_v1_62_0 = [
    { engine: 'quiz', sec: 20, pic: 'recycle_pet_bottle', q: { s: '寶特瓶是什麼材料做的?', f: '寶特瓶的材質是?' , en: 'What material is a PET bottle made of?' }, o: ['塑膠', '紙', '玻璃', '金屬'], oen: ['Plastic', 'Paper', 'Glass', 'Metal'], a: 0,
      why: { s: '寶特瓶是塑膠。', f: '寶特瓶是 PET 塑膠(1 號),由石油製成,回收後可以做成衣服纖維和新瓶子。', en: 'PET bottles are #1 PET plastic, made from petroleum. Once recycled, they can become clothing fibre or new bottles.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_pet_bottle', q: { s: '寶特瓶放進水裡會?', f: '空的寶特瓶(蓋上蓋子)放入水中會?' , en: 'What happens if you put a PET bottle in water?' }, o: ['浮起來', '沉下去', '溶化', '變大'], oen: ['It floats', 'It sinks', 'It dissolves', 'It grows bigger'], a: 0,
      why: { s: '裡面有空氣,會浮。', f: '密度比水小的東西會浮;裝滿空氣的寶特瓶整體密度小於水。', en: 'Anything less dense than water floats — a capped PET bottle full of air is less dense than water overall.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_pet_bottle', q: { s: '寶特瓶如果丟在野外要多久才會分解?', f: '寶特瓶在自然環境中分解需要?' , en: 'If a PET bottle is left in the wild, how long does it take to break down?' }, o: ['好幾百年', '三天', '一年', '一個星期'], oen: ['Hundreds of years', 'Three days', 'One year', 'One week'], a: 0,
      why: { s: '幾百年都還在。', f: '塑膠不容易被微生物分解,可能存在數百年,還會碎成微塑膠進入海洋和食物鏈。', en: 'Plastic resists being broken down by microbes and can last for hundreds of years — it also breaks into microplastics that enter the ocean and the food chain.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_pet_bottle', q: { s: '回收寶特瓶前要?', f: '寶特瓶回收的正確步驟是?' , en: 'What should you do before recycling a PET bottle?' }, o: ['沖洗、壓扁、瓶蓋分開', '連剩下的飲料一起丟', '裝滿水再一起丟', '用火燒掉比較乾淨'], oen: ['Rinse it and flatten it', 'Toss it with leftover drink still inside', 'Fill it with water first', 'Burn it — that\'s cleaner'], a: 0,
      why: { s: '沖一沖、壓扁。', f: '沖洗避免發臭發霉,壓扁節省空間;瓶蓋是不同塑膠,很多回收站要分開收。', en: 'Rinsing prevents odour and mould, and flattening saves space. The cap is a different type of plastic, so many recycling stations want it separated.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tin_can', q: { s: '鐵罐可以被磁鐵吸嗎?', f: '用磁鐵靠近鐵罐會?' , en: 'Will a magnet stick to a steel can?' }, o: ['會反彈', '會發熱', '會被吸住', '不會'], oen: ['Yes, it sticks', 'It heats up', 'It bounces off', 'No'], a: 2,
      why: { s: '鐵會被磁鐵吸。', f: '鐵、鎳、鈷會被磁鐵吸引;回收場就是用大磁鐵把鐵罐從垃圾中分出來。', en: 'Iron, nickel and cobalt are attracted to magnets — recycling facilities use big magnets to pull steel cans out of the trash.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tin_can', q: { s: '鐵罐放久了會怎樣?', f: '鐵製品放在潮濕的地方久了會?' , en: 'What happens to a steel can left out for a long time?' }, o: ['變金色', '變輕', '生鏽', '變軟'], oen: ['It turns gold', 'It gets lighter', 'It rusts', 'It gets soft'], a: 2,
      why: { s: '鐵碰到水和空氣會生鏽。', f: '鐵和空氣中的氧氣、水反應變成紅棕色的鐵鏽,所以鐵罐內側會鍍錫或塗膜防鏽。', en: 'Iron reacts with oxygen and water in the air to form reddish-brown rust, which is why the inside of steel cans is often tin-plated or coated to prevent it.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tin_can', q: { s: '怎麼防止鐵生鏽?', f: '防止鐵生鏽的方法是?' , en: 'How can you stop iron from rusting?' }, o: ['放在外面讓風吹乾', '每天用鹽水擦一擦', '常常泡在水裡清洗', '塗油漆或鍍其他金屬'], oen: ['Wrap it so it can\'t touch air or water', 'Rub it with salt water every day', 'Soak it in water often', 'Leave it outside to dry in the wind'], a: 3,
      why: { s: '把它包起來不碰到空氣和水。', f: '生鏽需要氧氣和水,塗漆、上油、鍍鋅都是把鐵和空氣、水隔開。', en: 'Rusting needs both oxygen and water — painting, oiling, or galvanising all work by keeping air and water away from the iron.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_soda_can', q: { s: '鋁罐可以被磁鐵吸嗎?', f: '用磁鐵靠近鋁罐會?' , en: 'Will a magnet stick to an aluminium can?' }, o: ['會被吸住', '會發光', '不會被吸', '會變熱'], oen: ['Yes, it sticks', 'It glows', 'No, it won\'t stick', 'It heats up'], a: 2,
      why: { s: '鋁不會被磁鐵吸。', f: '鋁不是磁性金屬,所以磁鐵吸不起來;這是分辨鐵罐和鋁罐最簡單的方法。', en: 'Aluminium isn\'t a magnetic metal, so a magnet can\'t pick it up — this is the easiest way to tell steel and aluminium cans apart.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_soda_can', q: { s: '鋁罐和鐵罐哪個比較輕?', f: '同樣大小的鋁罐和鐵罐,哪個較輕?' , en: 'Which is lighter, an aluminium can or a steel can?' }, o: ['一樣重', '要看飲料', '鋁罐', '鐵罐'], oen: ['They weigh the same', 'It depends on the drink', 'The aluminium can', 'The steel can'], a: 2,
      why: { s: '鋁很輕。', f: '鋁的密度約是鐵的三分之一,所以鋁罐輕又可以徒手壓扁。', en: 'Aluminium\'s density is only about a third of iron\'s, so aluminium cans are light enough to crush by hand.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_soda_can', q: { s: '回收鋁罐為什麼很划算?', f: '回收鋁罐比重新製造鋁能?' , en: 'Why is recycling aluminium cans such a good deal?' }, o: ['省下大量電力', '省下紙', '沒有差別', '省下水'], oen: ['It saves a huge amount of electricity', 'It saves paper', 'There\'s no difference', 'It saves water'], a: 0,
      why: { s: '回收鋁只要一點點電。', f: '從鋁土礦提煉鋁非常耗電,回收再熔化只需約 5% 的能源。', en: 'Refining aluminium from ore takes enormous amounts of electricity, but melting down recycled aluminium uses only about 5% as much energy.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_soda_can', q: { s: '鋁罐屬於哪一類回收物?', f: '鋁罐應丟進哪個回收桶?' , en: 'Which recycling category do aluminium cans belong to?' }, o: ['塑膠類', '一般垃圾', '紙類', '金屬類'], oen: ['Plastic', 'Regular trash', 'Paper', 'Metal'], a: 3,
      why: { s: '鋁是金屬。', f: '鐵罐、鋁罐、金屬蓋都屬金屬類回收。', en: 'Steel cans, aluminium cans, and metal lids are all recycled as metal.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_juice_pack', q: { s: '鋁箔包是由幾種材料組成的?', f: '鋁箔包的結構是?' , en: 'How many materials make up a juice box?' }, o: ['只有一層塑膠膜', '紙、塑膠膜、鋁箔三層', '只有薄薄的一層鋁', '只有厚厚的一層紙'], oen: ['Just one layer of plastic film', 'Three layers: paper, plastic film, and foil', 'Just a thin layer of aluminium', 'Just a thick layer of paper'], a: 1,
      why: { s: '紙加塑膠加鋁,三層。', f: '鋁箔包是複合材料,紙提供硬度、塑膠防水、鋁箔隔絕光和空氣,所以飲料能保存很久。', en: 'A juice box is a composite material — paper gives it rigidity, plastic film keeps it waterproof, and foil blocks light and air, which is why the drink inside lasts so long.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_juice_pack', q: { s: '鋁箔包為什麼能讓飲料保存很久?', f: '鋁箔包內的鋁箔層作用是?' , en: 'Why can juice boxes keep drinks fresh for so long?' }, o: ['讓包裝變重', '好看', '讓飲料變甜', '隔絕光線和空氣'], oen: ['It makes the packaging heavier', 'It looks nice', 'It makes the drink sweeter', 'It blocks out light and air'], a: 3,
      why: { s: '擋住光和空氣,飲料不會壞。', f: '光和氧氣會讓食物變質,鋁箔層把它們隔絕在外,所以常溫也能保存。', en: 'Light and oxygen make food spoil — the foil layer keeps both out, so the drink stays fresh even at room temperature.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_juice_pack', q: { s: '鋁箔包應該回收到哪裡?', f: '鋁箔包屬於哪類回收物?' , en: 'Which recycling category should a juice box go in?' }, o: ['塑膠類', '紙容器', '金屬類', '一般垃圾'], oen: ['Plastic', 'Paper carton', 'Metal', 'Regular trash'], a: 1,
      why: { s: '鋁箔包是紙容器。', f: '鋁箔包、紙餐盒、紙杯都算紙容器,要沖洗、壓扁後回收,回收廠會把紙漿分離。', en: 'Juice boxes, paper food containers, and paper cups all count as paper cartons — rinse and flatten them before recycling, and the facility will separate out the pulp.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_notebook', q: { s: '紙是用什麼做的?', f: '紙的主要原料是?' , en: 'What is paper made from?' }, o: ['樹木的纖維', '泥土', '石頭', '塑膠'], oen: ['Wood fibre', 'Soil', 'Rock', 'Plastic'], a: 0,
      why: { s: '紙是樹做的。', f: '紙由木材纖維製成;回收一噸紙約可少砍 17 棵樹。', en: 'Paper is made from wood fibre — recycling one tonne of paper saves roughly 17 trees.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_notebook', q: { s: '紙丟到水裡會?', f: '紙泡在水裡一段時間會?' , en: 'What happens if you put paper in water?' }, o: ['變硬', '變成塑膠', '浮著不變', '吸水變軟散開'], oen: ['It hardens', 'It turns into plastic', 'It floats unchanged', 'It absorbs water and falls apart'], a: 3,
      why: { s: '紙會吸水散掉。', f: '紙的纖維之間有空隙會吸水,纖維鬆開就散了,所以回收紙要保持乾燥。', en: 'There are gaps between paper fibres that soak up water — once the fibres loosen, the paper falls apart, so recyclable paper needs to stay dry.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_notebook', q: { s: '哪一種紙不能回收?', f: '下列哪種紙不適合回收?' , en: 'Which kind of paper can\'t be recycled?' }, o: ['筆記本', '紙箱', '報紙', '沾到油的紙'], oen: ['A notebook', 'A cardboard box', 'A newspaper', 'Paper stained with oil'], a: 3,
      why: { s: '沾油的紙不能回收。', f: '沾油、沾食物的紙(如披薩盒油漬處、用過的衛生紙)會污染紙漿,只能當一般垃圾。', en: 'Paper stained with oil or food — like a greasy pizza box or used tissue — contaminates the pulp and can only go in regular trash.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_notebook', q: { s: '筆記本的鐵圈要?', f: '回收有鐵圈的筆記本時應?' , en: 'What should you do with a notebook\'s metal spiral ring?' }, o: ['整本丟金屬', '丟一般垃圾', '拆掉鐵圈分開回收', '整本丟紙類'], oen: ['Remove the ring and recycle it separately', 'Throw the whole thing in regular trash', 'Throw the whole thing in metal recycling', 'Throw the whole thing in paper recycling'], a: 2,
      why: { s: '鐵圈和紙分開。', f: '不同材質要分開才能回收;鐵圈是金屬、紙頁是紙類。', en: 'Different materials need to be separated to be recycled — the ring is metal, the pages are paper.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_cardboard', q: { s: '紙箱可以回收幾次?', f: '紙纖維大約可以回收再製?' , en: 'About how many times can a cardboard box be recycled?' }, o: ['5~7 次', '無限次', '1 次', '不能回收'], oen: ['5 to 7 times', 'Unlimited times', 'Once', 'It can\'t be recycled'], a: 0,
      why: { s: '大約五到七次。', f: '每次回收紙纖維會變短變弱,約 5~7 次後就不能再造紙,所以還是要減少使用。', en: 'Paper fibres get shorter and weaker each time they\'re recycled — after about 5 to 7 times, they can\'t be made into paper anymore, so it\'s still worth using less.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_cardboard', q: { s: '紙箱為什麼要壓扁再回收?', f: '回收紙箱前壓扁的目的是?' , en: 'Why should you flatten a cardboard box before recycling it?' }, o: ['讓紙變重', '節省空間、方便運送', '好看', '讓紙變乾淨'], oen: ['To save space and make transport easier', 'To make the paper heavier', 'To make it look nicer', 'To make the paper cleaner'], a: 1,
      why: { s: '壓扁才不會佔空間。', f: '壓扁後回收車一次能載更多,減少運送次數和油耗。', en: 'A flattened box lets the recycling truck carry more at once, cutting down on trips and fuel.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_cardboard', q: { s: '瓦楞紙箱中間為什麼是波浪形?', f: '瓦楞紙板中間的波浪層作用是?' , en: 'Why is the middle layer of corrugated cardboard wavy?' }, o: ['波浪比較好看漂亮', '讓紙箱裡面可以透氣', '可以省下很多紙', '增加強度又能緩衝'], oen: ['To add strength and cushioning', 'The wave pattern just looks nice', 'So air can pass through the box', 'To save a lot of paper'], a: 3,
      why: { s: '波浪讓紙箱變硬又能防撞。', f: '波浪形結構像一排小拱門,能承受壓力又有彈性,和蜂巢原理類似。', en: 'The wavy structure is like a row of tiny arches — it can bear weight while staying springy, similar to how a honeycomb works.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_cardboard', q: { s: '紙箱淋濕了會?', f: '紙箱被雨淋濕後會?' , en: 'What happens to a cardboard box that gets soaked by rain?' }, o: ['變更硬', '變輕', '變成塑膠', '變軟不堅固'], oen: ['It gets harder', 'It gets lighter', 'It turns into plastic', 'It gets soft and loses its strength'], a: 3,
      why: { s: '濕掉就軟軟的。', f: '紙纖維吸水後失去強度,所以紙箱要放在乾燥處,濕掉的紙回收價值也降低。', en: 'Wet paper fibres lose their strength, so boxes should be kept dry — a soaked box is also worth less for recycling.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tissue', q: { s: '用過的面紙可以回收嗎?', f: '使用過的面紙、衛生紙應該?' , en: 'Can used tissue paper be recycled?' }, o: ['丟廚餘', '丟一般垃圾', '丟塑膠類', '丟紙類回收'], oen: ['Throw it in food waste', 'Throw it in regular trash', 'Throw it in plastic recycling', 'Throw it in paper recycling'], a: 1,
      why: { s: '用過的面紙不能回收。', f: '衛生紙、面紙纖維太短又沾了污物,設計成遇水就散,不能再造紙,要丟一般垃圾。', en: 'Tissue and toilet paper fibres are too short and already contaminated — they\'re designed to fall apart in water and can\'t be made into new paper, so they go in regular trash.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tissue', q: { s: '面紙為什麼碰到水就散?', f: '面紙遇水容易散開,是因為?' , en: 'Why does tissue paper fall apart when it gets wet?' }, o: ['纖維短又沒有加強', '面紙做得太薄了', '面紙上面有很多洞', '面紙的顏色是白色'], oen: ['Its fibres are short and unbonded on purpose', 'It\'s made too thin', 'It has lots of tiny holes', 'It\'s coloured white'], a: 0,
      why: { s: '纖維短短的,一泡水就散。', f: '面紙、衛生紙的纖維刻意做得短且不加黏合劑,才能在馬桶裡分解,不會堵塞。', en: 'Tissue and toilet paper are deliberately made with short fibres and no binding agent, so they break down in the toilet instead of clogging it.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tissue', q: { s: '省紙的好方法是?', f: '減少衛生紙、面紙使用的方法是?' , en: 'What\'s a good way to save paper tissue?' }, o: ['多買一點', '用濕紙巾', '用手帕、抹布代替', '用兩張'], oen: ['Use a handkerchief instead of tossing it constantly', 'Buy more of it', 'Use wet wipes instead', 'Use two sheets at once'], a: 2,
      why: { s: '用手帕就不用一直丟。', f: '「減量」比「回收」更環保:少用一次性產品,才是從源頭減少垃圾。', en: '\'Reducing\' is even more eco-friendly than \'recycling\' — using fewer disposable products cuts down on waste at the source.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_shampoo', q: { s: '洗髮精瓶是什麼材料?', f: '洗髮精瓶子的材質通常是?' , en: 'What material is a shampoo bottle usually made of?' }, o: ['金屬', '玻璃', '紙', '塑膠'], oen: ['A plastic bottle', 'Metal', 'Glass', 'Paper'], a: 3,
      why: { s: '是塑膠瓶。', f: '洗髮精瓶多是 HDPE(2 號)塑膠,比寶特瓶硬,回收後可做花盆、水管。', en: 'Shampoo bottles are usually #2 HDPE plastic — sturdier than a PET bottle, and can be recycled into flowerpots or pipes.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_shampoo', q: { s: '洗髮精瓶回收前要?', f: '回收洗髮精瓶的正確做法是?' , en: 'What should you do before recycling a shampoo bottle?' }, o: ['用完沖乾淨', '裝水丟', '燒掉', '整瓶還有洗髮精就丟'], oen: ['Rinse it out first', 'Fill it with water and throw it away', 'Burn it', 'Throw it away with shampoo still inside'], a: 0,
      why: { s: '沖乾淨再回收。', f: '殘留的洗髮精會污染其他回收物,也讓回收廠處理更麻煩。', en: 'Leftover shampoo can contaminate other recyclables and makes things harder for the recycling facility.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_shampoo', q: { s: '買補充包比買新瓶子?', f: '選擇補充包而不是新瓶子,可以?' , en: 'What\'s the benefit of buying a refill pouch instead of a new bottle?' }, o: ['沒有差別', '比較貴', '減少塑膠垃圾', '增加垃圾'], oen: ['The refill pouch uses far less plastic', 'No difference', 'It\'s more expensive', 'It creates more waste'], a: 2,
      why: { s: '補充包塑膠少很多。', f: '補充包的塑膠用量只有硬瓶的幾分之一,舊瓶重複使用就是「再利用」。', en: 'A refill pouch uses only a fraction of the plastic of a rigid bottle — reusing the old bottle is \'reuse\' in action.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_shampoo', q: { s: '塑膠是用什麼做的?', f: '大多數塑膠的原料是?' , en: 'What is most plastic made from?' }, o: ['石油', '沙子', '鐵礦', '樹木'], oen: ['Petroleum', 'Sand', 'Iron ore', 'Wood'], a: 0,
      why: { s: '塑膠是石油做的。', f: '塑膠由石油提煉而成,石油是有限資源,燃燒也會排放溫室氣體。', en: 'Plastic is refined from petroleum, a limited resource, and burning it releases greenhouse gases too.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_broken_bowl', q: { s: '破掉的陶瓷碗要丟哪裡?', f: '破碗、破盤子屬於?' , en: 'Where should a broken ceramic bowl go?' }, o: ['玻璃回收', '金屬回收', '一般垃圾(包好)', '紙類回收'], oen: ['Regular trash (wrapped up)', 'Glass recycling', 'Metal recycling', 'Paper recycling'], a: 2,
      why: { s: '陶瓷不能回收,要包好丟垃圾。', f: '陶瓷高溫燒成後無法再熔化重製,不能回收;要用報紙包好、標示「小心」避免割傷清潔人員。', en: 'Once ceramic is fired at high temperature it can\'t be melted down and remade, so it can\'t be recycled — wrap it in newspaper and mark it \'careful\' so sanitation workers don\'t get cut.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_broken_bowl', q: { s: '陶瓷碗是用什麼做的?', f: '陶瓷的原料是?' , en: 'What is ceramic made from?' }, o: ['石油', '塑膠', '黏土燒製', '金屬'], oen: ['Petroleum', 'Plastic', 'Fired clay', 'Metal'], a: 2,
      why: { s: '土燒成的。', f: '陶瓷是黏土成型後高溫燒製而成,鶯歌就是台灣有名的陶瓷產地。', en: 'Ceramic is shaped from clay, then fired at high temperature — Yingge is Taiwan\'s famous ceramics town.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_broken_bowl', q: { s: '陶瓷碗裝熱湯,碗外面?', f: '陶瓷碗裝熱湯時碗壁?' , en: 'When a ceramic bowl holds hot soup, the outside of the bowl?' }, o: ['反而會變得冰冰的', '會慢慢變熱但不太燙', '馬上就燙得拿不住', '完全不會有一點熱'], oen: ['Slowly warms up but isn\'t too hot', 'Actually feels cold', 'Gets too hot to hold right away', 'Doesn\'t get warm at all'], a: 1,
      why: { s: '陶瓷傳熱慢。', f: '陶瓷是熱的不良導體,所以碗可以端,但也不像保麗龍那樣完全不熱。', en: 'Ceramic is a poor conductor of heat, so you can hold the bowl — though it\'s not a perfect insulator like styrofoam either.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_broken_bowl', q: { s: '玻璃和陶瓷哪個可以回收?', f: '下列何者可回收?' , en: 'Which of these can be recycled — glass or ceramic?' }, o: ['陶瓷碗', '玻璃瓶', '燈泡', '鏡子'], oen: ['Glass bottle', 'Ceramic bowl', 'Light bulb', 'Mirror'], a: 1,
      why: { s: '玻璃瓶可以回收。', f: '玻璃瓶熔化後可以重製;陶瓷、鏡子(有鍍膜)、燈泡(材質混合)都不能進玻璃回收。', en: 'A melted-down glass bottle can be remade — but ceramic, mirrors (which have a coating), and light bulbs (mixed materials) can\'t go in glass recycling.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_straw', q: { s: '塑膠吸管為什麼對海洋不好?', f: '塑膠吸管流入海洋會?' , en: 'Why are plastic straws bad for the ocean?' }, o: ['幫魚呼吸', '變成珊瑚', '溶解', '被海龜等生物誤食'], oen: ['Sea creatures like turtles mistake them for food', 'They help fish breathe', 'They turn into coral', 'They dissolve'], a: 3,
      why: { s: '海龜會誤吞吸管。', f: '吸管輕又小,容易隨雨水流入海洋,被海龜、海鳥誤食,卡在鼻孔或腸胃。', en: 'Straws are light and small, so they easily wash into the ocean with rainwater, where turtles and seabirds mistake them for food and get them stuck in their nose or gut.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_straw', q: { s: '用過的塑膠吸管要?', f: '使用過的塑膠吸管應該?' , en: 'What should you do with a used plastic straw?' }, o: ['紙類回收', '丟一般垃圾', '塑膠回收', '丟廚餘'], oen: ['Regular trash', 'Paper recycling', 'Plastic recycling', 'Food waste'], a: 1,
      why: { s: '吸管太小太髒,不回收。', f: '吸管體積小、常沾食物殘渣,回收價值低,大多數縣市列為一般垃圾;最好的方式是不用。', en: 'Straws are small and often covered in food residue, so their recycling value is low — most counties treat them as regular trash. Best of all is not using one.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_straw', q: { s: '代替塑膠吸管的好選擇?', f: '環保的吸管替代品是?' , en: 'What\'s a good eco-friendly alternative to plastic straws?' }, o: ['紙杯', '更多塑膠吸管', '不鏽鋼或玻璃吸管', '塑膠袋'], oen: ['A reusable straw', 'Paper cups', 'More plastic straws', 'Plastic bags'], a: 2,
      why: { s: '用可以重複用的吸管。', f: '不鏽鋼、玻璃、竹製吸管可以重複使用;或直接不用吸管。', en: 'Stainless steel, glass, or bamboo straws can be reused — or you can just skip the straw altogether.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_bin_paper', q: { s: '回收的英文 3R 是?', f: '環保 3R 指的是?' , en: 'What does the \'3R\' of recycling stand for?' }, o: ['跑步、閱讀、休息', '紅、綠、藍', '紙、鐵、塑膠', '減量、重複使用、回收'], oen: ['Reduce, Reuse, Recycle', 'Run, Read, Rest', 'Red, Green, Blue', 'Paper, Iron, Plastic'], a: 3,
      why: { s: '減量、再利用、回收。', f: 'Reduce 減量、Reuse 重複使用、Recycle 回收;順序也代表重要性,減量最重要。', en: 'Reduce, Reuse, Recycle — the order also reflects priority, with reducing being the most important.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_bin_plas', q: { s: '塑膠回收標誌裡的數字代表?', f: '塑膠製品底部三角形裡的數字表示?' , en: 'What does the number inside the plastic recycling triangle mean?' }, o: ['重量', '塑膠的種類', '可以回收幾次', '價錢'], oen: ['The type of plastic', 'Weight', 'How many times it can be recycled', 'Price'], a: 1,
      why: { s: '數字是塑膠的種類。', f: '1 號 PET(寶特瓶)、2 號 HDPE(洗髮精瓶)、5 號 PP(便當盒)…數字代表材質,方便分類。', en: '#1 is PET (like a soda bottle), #2 is HDPE (like a shampoo bottle), #5 is PP (like a lunchbox)... the number identifies the material, making sorting easier.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_bin_metal', q: { s: '哪一種材料可以無限次回收?', f: '可以重複熔化再製、幾乎不會變差的材料是?' , en: 'Which material can be recycled an unlimited number of times?' }, o: ['金屬和玻璃', '紙', '塑膠', '木頭'], oen: ['Metal and glass', 'Paper', 'Plastic', 'Wood'], a: 0,
      why: { s: '金屬熔化再做,品質不變。', f: '金屬、玻璃可以無限次回收;紙纖維會變短、塑膠會變差,只能回收有限次數。', en: 'Metal and glass can be recycled endlessly without losing quality — paper fibres get shorter and plastic degrades, so those can only be recycled a limited number of times.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_bin_trash', q: { s: '廚餘應該怎麼處理?', f: '吃剩的食物、果皮應?' , en: 'How should food waste be handled?' }, o: ['丟塑膠類', '丟水溝', '丟紙類', '丟廚餘桶或做堆肥'], oen: ['Put it in a food-waste bin or compost it', 'Throw it in plastic recycling', 'Throw it down the drain', 'Throw it in paper recycling'], a: 3,
      why: { s: '廚餘可以變肥料。', f: '廚餘可以做堆肥或養豬,分解後變成肥料回到土裡,不用進焚化爐。', en: 'Food waste can be composted or fed to pigs — it breaks down into fertiliser that returns to the soil, without ever going to the incinerator.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_bin_trash', q: { s: '垃圾燒掉之後會?', f: '一般垃圾送到焚化爐燃燒後?' , en: 'What happens after trash is incinerated?' }, o: ['變成可以種菜的土', '變成灰和廢氣還能發電', '完全消失什麼都不剩', '變成乾淨的水流走'], oen: ['It turns into ash and exhaust, and the heat can generate power', 'It becomes soil good for growing vegetables', 'It completely disappears, nothing left', 'It turns into clean water and washes away'], a: 1,
      why: { s: '燒完剩灰,熱可以發電。', f: '焚化爐燃燒垃圾產生的熱能用來發電,但也產生廢氣和底渣,所以減少垃圾最重要。', en: 'The heat from burning trash is used to generate electricity, but it also produces exhaust gas and ash residue — which is why reducing trash in the first place matters most.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_pet_bottle', q: { s: '哪一種東西會浮在水上?', f: '下列何者放入水中會浮?' , en: 'Which of these floats on water?' }, o: ['鐵釘', '保麗龍', '石頭', '玻璃珠'], oen: ['Styrofoam', 'An iron nail', 'A rock', 'A glass marble'], a: 1,
      why: { s: '保麗龍最輕。', f: '保麗龍密度極小會浮;鐵、石頭、玻璃密度比水大會沉。', en: 'Styrofoam has an extremely low density and floats; iron, rock and glass are all denser than water and sink.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tin_can', q: { s: '把鐵罐和鋁罐分開最快的方法?', f: '分辨鐵罐和鋁罐的簡單方法是?' , en: 'What\'s the fastest way to separate steel cans from aluminium cans?' }, o: ['用磁鐵吸', '看顏色', '用火燒', '用水泡'], oen: ['Use a magnet', 'Look at the colour', 'Burn them', 'Soak them in water'], a: 0,
      why: { s: '磁鐵吸得住的是鐵。', f: '磁鐵只吸鐵不吸鋁;回收場用電磁鐵自動把鐵罐分出來。', en: 'A magnet sticks to steel but not aluminium — recycling facilities use electromagnets to automatically pull out the steel cans.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_juice_pack', q: { s: '哪些包裝算「紙容器」?', f: '下列何者屬於紙容器回收?' , en: 'Which packages count as \'paper cartons\'?' }, o: ['紙箱', '筆記本', '鋁箔包和紙杯', '報紙'], oen: ['Juice boxes and paper cups', 'Cardboard boxes', 'Notebooks', 'Newspapers'], a: 2,
      why: { s: '鋁箔包、紙杯裡面有塑膠膜。', f: '紙容器指內層有防水膜的紙製包裝,和純紙類分開處理。', en: '\'Paper cartons\' means paper packaging with a waterproof lining inside — they\'re handled separately from plain paper.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_notebook', q: { s: '做一噸再生紙比原生紙可以省?', f: '使用回收紙製造新紙的好處是?' , en: 'What does making a ton of recycled paper save compared to new paper?' }, o: ['少砍樹、省水省電', '紙變更白', '紙變更貴', '沒有好處'], oen: ['Fewer trees cut down, and less water and electricity used', 'It makes the paper whiter', 'It makes the paper more expensive', 'There\'s no benefit'], a: 0,
      why: { s: '少砍樹、省水電。', f: '再生紙製程比從木材造紙省約 60% 能源和大量水,還減少砍伐森林。', en: 'Making recycled paper uses about 60% less energy and a huge amount less water than making paper from wood, and it also means fewer trees cut down.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_shampoo', q: { s: '哪一種塑膠製品最好不要一直用?', f: '為了健康和環保,最該減少的是?' , en: 'Which plastic product is best to avoid using all the time?' }, o: ['塑膠椅', '水壺', '塑膠尺', '一次性塑膠餐具'], oen: ['Disposable plastic tableware', 'A plastic chair', 'A water bottle', 'A plastic ruler'], a: 3,
      why: { s: '用一次就丟的最浪費。', f: '一次性餐具、塑膠袋用幾分鐘就變垃圾,是海洋塑膠的主要來源。', en: 'Disposable tableware and plastic bags turn into trash within minutes of use — they\'re a major source of ocean plastic.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_soda_can', q: { s: '喝完飲料的鋁罐壓扁再丟,是為了?', f: '壓扁鋁罐的目的是?' , en: 'Why should you flatten an aluminium can before throwing it away?' }, o: ['省空間方便回收', '讓鋁變重', '好看', '讓鋁變乾淨'], oen: ['Flattening saves space', 'To make the aluminium heavier', 'To make it look nicer', 'To make the aluminium cleaner'], a: 0,
      why: { s: '壓扁不佔空間。', f: '壓扁後回收袋和回收車能裝更多,減少運輸次數。', en: 'A flattened can lets recycling bags and trucks hold more, cutting down on the number of trips needed.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_cardboard', q: { s: '回收物如果混到垃圾會?', f: '把垃圾丟進回收桶會造成?' , en: 'What happens if trash gets mixed into the recycling bin?' }, o: ['混在一起反而更好回收', '沒關係工廠會分開', '整袋回收物可能不能用', '回收速度會變得更快'], oen: ['Dirty waste can contaminate the whole batch of recyclables', 'Mixing them actually makes recycling easier', 'It\'s fine, the factory will sort it out', 'Recycling gets faster'], a: 2,
      why: { s: '髒東西會污染整袋回收。', f: '廚餘、油污混進回收物會讓紙、塑膠發霉變質,整批只能當垃圾燒掉,所以分類要正確。', en: 'Food scraps or oil mixed into recyclables can make paper and plastic mouldy or spoiled, so the whole batch may have to be burned as trash instead — sorting correctly really matters.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_straw', q: { s: '海洋裡的塑膠碎成很小很小叫?', f: '塑膠在海洋中碎裂成極小的顆粒稱為?' , en: 'What is it called when plastic in the ocean breaks into tiny pieces?' }, o: ['細沙', '海鹽', '塑膠雨', '微塑膠'], oen: ['Microplastic, too small to see', 'Fine sand', 'Sea salt', 'Plastic rain'], a: 3,
      why: { s: '小到看不見的微塑膠。', f: '微塑膠小於 5 公釐,會被小魚小蝦吃下肚,再沿食物鏈回到人類餐桌。', en: 'Microplastics are smaller than 5mm — small fish and shrimp eat them, and they travel up the food chain back to our dinner tables.' } },
    { engine: 'quiz', sec: 20, pic: 'recycle_tissue', q: { s: '哪一種行為最環保?', f: '下列哪個行為最能減少垃圾?' , en: 'Which habit is the most eco-friendly?' }, o: ['用一次性餐具', '每天買瓶裝水', '多用免洗筷', '自備水壺和餐具'], oen: ['Bringing your own bottle and utensils so you make no waste', 'Using disposable tableware', 'Buying bottled water every day', 'Using lots of disposable chopsticks'], a: 3,
      why: { s: '自己帶,就不會產生垃圾。', f: '自備水壺、餐具、購物袋,從源頭減量,比回收更有效。', en: 'Bringing your own water bottle, utensils, and shopping bag reduces waste at the source — even more effective than recycling.' } },
    /* ★ v1.3.1 鋁箔包是環保署公告應回收物(紙容器類),原歸一般垃圾有誤 → 改紙類 */
    { t: '喝完的鋁箔包飲料(沖一下、壓扁)', ten: 'An empty juice box (rinse and flatten it)', pic: 'recycle_juice_pack', b: 'paper',
      why: { s: '鋁箔包是「紙容器」,要回收,跟紙類一起。',
             f: '鋁箔包是紙、塑膠膜、鋁箔三層複合的「紙容器」,是政府公告的應回收物;回收廠會把紙漿分離再利用。丟之前先沖洗、壓扁,學校若有「紙容器」桶就放那裡。', en: 'A juice box is a \'paper carton\' — it\'s paper, plastic film and foil layered together, and it\'s on the government\'s official recyclables list. Rinse and flatten it first, and put it with paper (or a paper-carton bin if your school has one).' } },
    { t: '寫完的作業簿', ten: 'A finished homework notebook', pic: 'recycle_notebook', b: 'paper',
      why: { s: '紙做的,丟紙類。',
             f: '紙類回收後可再製成再生紙。要注意的是:紙張若沾到油污或有塑膠護貝就不能回收。', en: "It's made of paper, so it goes with paper. One thing to watch for: paper stained with oil or laminated with plastic can't be recycled." } },
    { t: '寶特瓶(記得先壓扁)', ten: 'A PET bottle (remember to flatten it first)', pic: 'recycle_pet_bottle', b: 'plas',
      why: { s: '寶特瓶是塑膠。',
             f: '寶特瓶材質為 PET(聚對苯二甲酸乙二酯),回收後可抽成聚酯纖維做衣服。壓扁能省下運送空間。', en: 'PET bottles are plastic. The material can be spun into polyester fibre for clothes after recycling — flattening it saves space for transport.' } },
    { t: '午餐吃完的鐵鋁罐', ten: 'An empty can from lunch', pic: 'recycle_tin_can', b: 'metal',
      why: { s: '罐子是金屬做的。',
             f: '鐵罐與鋁罐都屬金屬回收。鋁的回收最有價值:再生鋁只需原生鋁約 5% 的能源。', en: 'Cans are made of metal. Both steel and aluminium cans are recycled as metal — recycled aluminium is especially valuable, needing only about 5% of the energy of making it from scratch.' } },
    { t: '用過的衛生紙', ten: 'Used tissue paper', pic: 'recycle_tissue', b: 'trash',
      why: { s: '衛生紙不能回收喔。',
             f: '衛生紙纖維短且已受污染,不列入紙類回收,應丟一般垃圾。這是最常見的分類錯誤之一。', en: 'Tissue paper can\'t be recycled — its fibres are too short and it\'s already contaminated, so it goes in regular trash. This is one of the most common sorting mistakes.' } },
    { t: '洗髮精的空瓶子', ten: 'An empty shampoo bottle', pic: 'recycle_shampoo', b: 'plas',
      why: { s: '瓶子是塑膠的。',
             f: '塑膠容器回收前要沖洗乾淨、瓶蓋分開。瓶身多為 HDPE 或 PP,可再製成塑膠棧板等。', en: 'The bottle is plastic. Rinse it out and separate the cap before recycling — the bottle itself is usually HDPE or PP, which can be remade into things like plastic pallets.' } },
    { t: '拆開的紙箱', ten: 'A flattened cardboard box', pic: 'recycle_cardboard', b: 'paper',
      why: { s: '紙箱也是紙。',
             f: '瓦楞紙箱是紙類回收的大宗,回收前要拆平、去除膠帶。', en: 'Cardboard boxes are a big part of paper recycling — flatten them and remove any tape first.' } },
    { t: '破掉的陶瓷碗', ten: 'A broken ceramic bowl', pic: 'recycle_broken_bowl', b: 'trash',
      why: { s: '碗破了不能回收,要小心包好再丟。',
             f: '陶瓷與玻璃的熔點不同,混入玻璃回收會造成整批報廢,故歸一般垃圾;丟棄前應用報紙包好避免清潔隊員受傷。', en: 'Ceramic and glass melt at different temperatures, so ceramic mixed into glass recycling ruins the whole batch — it goes in regular trash. Wrap broken pieces in newspaper first so sanitation workers don\'t get cut.' } },
    { t: '喝完的鋁罐汽水', ten: 'An empty soda can', pic: 'recycle_soda_can', b: 'metal',
      why: { s: '鋁罐是金屬。',
             f: '鋁罐可無限次回收且品質不衰減,是回收價值最高的日常容器之一。', en: 'Aluminium cans are metal, and can be recycled endlessly without losing quality — one of the most valuable everyday containers to recycle.' } },
    { t: '塑膠吸管', ten: 'A plastic straw', pic: 'recycle_straw', b: 'plas',
      why: { s: '吸管是塑膠做的。',
             f: '吸管雖是塑膠,但太細小容易在分選機漏掉;台灣自 2019 年起限制內用一次性塑膠吸管,少用才是根本辦法。', en: 'Straws are plastic, but they\'re so small they often slip through sorting machines. Taiwan has restricted disposable plastic straws for dine-in use since 2019 — using fewer is the real solution.' } },
    { t: "看完的報紙", ten: 'A newspaper you\'ve finished reading', b: 'paper',
      why: { s: "紙做的,丟紙類。", f: "報紙可回收再製成再生紙;若被雨淋濕發霉就不能回收。", en: "It's paper, so it's recycled into new paper — but if it's gotten rained on and gone mouldy, it can't be recycled." } },
    { t: "喝完的牛奶紙盒(沖乾淨)", ten: 'An empty milk carton (rinsed clean)', b: 'paper',
      why: { s: "牛奶盒是紙容器。", f: "牛奶紙盒內層有塑膠膜,屬「紙容器」類,沖洗壓扁後回收,學校若有紙容器桶請放那裡。", en: "A milk carton has a plastic lining inside, so it's a 'paper carton' — rinse and flatten it, and use a paper-carton bin if your school has one." } },
    { t: "用過的影印紙", ten: 'Used photocopy paper', b: 'paper',
      why: { s: "紙類回收。", f: "影印紙是最好回收的紙類,可先當計算紙用完兩面再回收。", en: "Photocopy paper recycles easily — use both sides as scratch paper first before recycling it." } },
    { t: "喝完飲料的紙杯(沖乾淨)", ten: 'An empty drink cup (rinsed clean)', b: 'paper',
      why: { s: "紙杯也是紙容器。", f: "紙杯內層有防水膜,屬紙容器類;要倒掉飲料、沖洗後回收。", en: "Paper cups have a waterproof lining inside, so they're 'paper cartons' too — empty and rinse before recycling." } },
    { t: "過期的雜誌", ten: 'An old magazine', b: 'paper',
      why: { s: "紙類回收。", f: "雜誌雖然亮面,仍可回收;釘書針不用拆。", en: "Even with its glossy cover, a magazine can still be recycled — no need to remove the staples." } },
    { t: "喝完的優酪乳塑膠瓶", ten: 'An empty yogurt drink bottle', b: 'plas',
      why: { s: "塑膠瓶要回收。", f: "優酪乳瓶多為 PE/PP 塑膠,沖洗乾淨後回收。", en: "It's a plastic bottle — usually PE or PP plastic — rinse it clean before recycling." } },
    { t: "裝過東西的塑膠袋", ten: 'A used plastic bag', b: 'plas',
      why: { s: "塑膠袋是塑膠類。", f: "乾淨的塑膠袋可回收;沾滿油污的要當一般垃圾。", en: "A clean plastic bag can be recycled — but one covered in grease or oil goes in regular trash." } },
    { t: "寶特瓶的瓶蓋", ten: 'A PET bottle cap', b: 'plas',
      why: { s: "瓶蓋也是塑膠。", f: "瓶蓋多為 PP 或 PE 塑膠,可與瓶身一起回收。", en: "Bottle caps are plastic too — usually PP or PE — and can be recycled along with the bottle." } },
    { t: "洗乾淨的塑膠便當盒", ten: 'A clean plastic lunchbox', b: 'plas',
      why: { s: "塑膠容器洗乾淨就能回收。", f: "塑膠餐盒要先把油和菜渣洗掉再回收,否則會污染整批回收物。", en: "Wash off any oil and food scraps first — otherwise it can contaminate the whole batch of recycling." } },
    { t: "破掉的塑膠水桶", ten: 'A broken plastic bucket', b: 'plas',
      why: { s: "塑膠類。", f: "大件塑膠製品也屬塑膠類回收,太大可交給清潔隊。", en: "Large plastic items are recycled as plastic too — if it's too big, hand it to the sanitation crew." } },
    { t: "生鏽的鐵釘", ten: 'A rusty nail', b: 'metal',
      why: { s: "鐵做的,金屬類。", f: "鐵釘是鐵製品,可回收熔煉再利用;要注意不要刺傷手。", en: "It's made of iron, so it's recycled as metal and can be melted down and reused — just be careful not to prick your hand." } },
    { t: "吃完的鮪魚罐頭(洗過)", ten: 'An empty tuna can (washed)', b: 'metal',
      why: { s: "罐頭是金屬。", f: "罐頭多為馬口鐵,沖洗後回收,鐵罐可被磁鐵吸起來。", en: "Cans are usually tin-plated steel — rinse and recycle. A magnet will stick to a steel can." } },
    { t: "用過的鋁箔烤盤(擦乾淨)", ten: 'A used foil baking tray (wiped clean)', b: 'metal',
      why: { s: "鋁箔盤是鋁製的金屬。", f: "鋁製品輕又不會被磁鐵吸,擦掉食物殘渣後回收。", en: "Foil trays are aluminium — light, and won't stick to a magnet. Wipe off any food residue before recycling." } },
    { t: "不能用的舊鑰匙", ten: 'An old key that no longer works', b: 'metal',
      why: { s: "鑰匙是金屬。", f: "鑰匙多為銅或鋅合金,屬金屬類回收。", en: "Keys are usually made of copper or zinc alloy, so they're recycled as metal." } },
    { t: "壞掉的鐵製便當盒", ten: 'A broken stainless steel lunchbox', b: 'metal',
      why: { s: "不鏽鋼便當盒是金屬。", f: "不鏽鋼餐具屬金屬類,回收後可再製成新的鋼材。", en: "Stainless steel tableware is metal — once recycled, it can be remade into new steel." } },
    { t: "用過的口罩", ten: 'A used face mask', b: 'trash',
      why: { s: "口罩用過有細菌,丟一般垃圾。", f: "口罩有病菌且材質混合,不能回收,要當一般垃圾丟掉。", en: "A used mask carries germs and is made of mixed materials, so it can't be recycled — it goes in regular trash." } },
    { t: "用過的免洗竹筷", ten: 'Used disposable bamboo chopsticks', b: 'trash',
      why: { s: "竹筷是一般垃圾。", f: "竹筷沾過食物且是竹木材質,不在回收項目內,屬一般垃圾。", en: "Bamboo chopsticks are wood, and they've touched food, so they're not on the recycling list — they're regular trash." } },
    { t: "嚼過的口香糖", ten: 'Chewed gum', b: 'trash',
      why: { s: "包起來丟一般垃圾。", f: "口香糖是合成膠,不能回收;要用紙包好再丟,不能亂吐。", en: "Gum is a synthetic rubber and can't be recycled — wrap it in paper before throwing it away, and never spit it out just anywhere." } },
    { t: "削鉛筆的木屑", ten: 'Pencil shavings', b: 'trash',
      why: { s: "木屑是一般垃圾。", f: "鉛筆屑是木頭和筆芯粉末,不屬於任何回收類別。", en: "Pencil shavings are a mix of wood and graphite dust, and don't belong to any recycling category." } },
    { t: "擦過地板的髒抹布", ten: 'A dirty rag used to clean the floor', b: 'trash',
      why: { s: "髒抹布是一般垃圾。", f: "破舊髒污的布類無法回收,屬一般垃圾;乾淨的舊衣才能進舊衣回收箱。", en: "Worn, dirty cloth can't be recycled and goes in regular trash — only clean old clothes belong in a used-clothing donation bin." } }
];
